
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
export const prismaVersion: PrismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Package: 'Package',
  Bookings: 'Bookings',
  Payment: 'Payment',
  DayItinerary: 'DayItinerary',
  FeaturedItems: 'FeaturedItems',
  IncludedItems: 'IncludedItems',
  ExcludedItems: 'ExcludedItems',
  Blogs: 'Blogs',
  BlogImages: 'BlogImages',
  BlogCategory: 'BlogCategory',
  Destinations: 'Destinations',
  DestinationFAQ: 'DestinationFAQ',
  Testimonials: 'Testimonials'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "package" | "bookings" | "payment" | "dayItinerary" | "featuredItems" | "includedItems" | "excludedItems" | "blogs" | "blogImages" | "blogCategory" | "destinations" | "destinationFAQ" | "testimonials"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Package: {
      payload: Prisma.$PackagePayload<ExtArgs>
      fields: Prisma.PackageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PackageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PackageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>
        }
        findFirst: {
          args: Prisma.PackageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PackageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>
        }
        findMany: {
          args: Prisma.PackageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>[]
        }
        create: {
          args: Prisma.PackageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>
        }
        createMany: {
          args: Prisma.PackageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PackageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>[]
        }
        delete: {
          args: Prisma.PackageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>
        }
        update: {
          args: Prisma.PackageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>
        }
        deleteMany: {
          args: Prisma.PackageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PackageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PackageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>[]
        }
        upsert: {
          args: Prisma.PackageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PackagePayload>
        }
        aggregate: {
          args: Prisma.PackageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePackage>
        }
        groupBy: {
          args: Prisma.PackageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PackageGroupByOutputType>[]
        }
        count: {
          args: Prisma.PackageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PackageCountAggregateOutputType> | number
        }
      }
    }
    Bookings: {
      payload: Prisma.$BookingsPayload<ExtArgs>
      fields: Prisma.BookingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BookingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BookingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>
        }
        findFirst: {
          args: Prisma.BookingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BookingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>
        }
        findMany: {
          args: Prisma.BookingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>[]
        }
        create: {
          args: Prisma.BookingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>
        }
        createMany: {
          args: Prisma.BookingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BookingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>[]
        }
        delete: {
          args: Prisma.BookingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>
        }
        update: {
          args: Prisma.BookingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>
        }
        deleteMany: {
          args: Prisma.BookingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BookingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BookingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>[]
        }
        upsert: {
          args: Prisma.BookingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingsPayload>
        }
        aggregate: {
          args: Prisma.BookingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBookings>
        }
        groupBy: {
          args: Prisma.BookingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.BookingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookingsCountAggregateOutputType> | number
        }
      }
    }
    Payment: {
      payload: Prisma.$PaymentPayload<ExtArgs>
      fields: Prisma.PaymentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PaymentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PaymentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>
        }
        findFirst: {
          args: Prisma.PaymentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PaymentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>
        }
        findMany: {
          args: Prisma.PaymentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>[]
        }
        create: {
          args: Prisma.PaymentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>
        }
        createMany: {
          args: Prisma.PaymentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PaymentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>[]
        }
        delete: {
          args: Prisma.PaymentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>
        }
        update: {
          args: Prisma.PaymentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>
        }
        deleteMany: {
          args: Prisma.PaymentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PaymentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PaymentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>[]
        }
        upsert: {
          args: Prisma.PaymentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentPayload>
        }
        aggregate: {
          args: Prisma.PaymentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePayment>
        }
        groupBy: {
          args: Prisma.PaymentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PaymentGroupByOutputType>[]
        }
        count: {
          args: Prisma.PaymentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PaymentCountAggregateOutputType> | number
        }
      }
    }
    DayItinerary: {
      payload: Prisma.$DayItineraryPayload<ExtArgs>
      fields: Prisma.DayItineraryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DayItineraryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DayItineraryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>
        }
        findFirst: {
          args: Prisma.DayItineraryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DayItineraryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>
        }
        findMany: {
          args: Prisma.DayItineraryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>[]
        }
        create: {
          args: Prisma.DayItineraryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>
        }
        createMany: {
          args: Prisma.DayItineraryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DayItineraryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>[]
        }
        delete: {
          args: Prisma.DayItineraryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>
        }
        update: {
          args: Prisma.DayItineraryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>
        }
        deleteMany: {
          args: Prisma.DayItineraryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DayItineraryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DayItineraryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>[]
        }
        upsert: {
          args: Prisma.DayItineraryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DayItineraryPayload>
        }
        aggregate: {
          args: Prisma.DayItineraryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDayItinerary>
        }
        groupBy: {
          args: Prisma.DayItineraryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DayItineraryGroupByOutputType>[]
        }
        count: {
          args: Prisma.DayItineraryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DayItineraryCountAggregateOutputType> | number
        }
      }
    }
    FeaturedItems: {
      payload: Prisma.$FeaturedItemsPayload<ExtArgs>
      fields: Prisma.FeaturedItemsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FeaturedItemsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FeaturedItemsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>
        }
        findFirst: {
          args: Prisma.FeaturedItemsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FeaturedItemsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>
        }
        findMany: {
          args: Prisma.FeaturedItemsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>[]
        }
        create: {
          args: Prisma.FeaturedItemsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>
        }
        createMany: {
          args: Prisma.FeaturedItemsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FeaturedItemsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>[]
        }
        delete: {
          args: Prisma.FeaturedItemsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>
        }
        update: {
          args: Prisma.FeaturedItemsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>
        }
        deleteMany: {
          args: Prisma.FeaturedItemsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FeaturedItemsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FeaturedItemsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>[]
        }
        upsert: {
          args: Prisma.FeaturedItemsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FeaturedItemsPayload>
        }
        aggregate: {
          args: Prisma.FeaturedItemsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFeaturedItems>
        }
        groupBy: {
          args: Prisma.FeaturedItemsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FeaturedItemsGroupByOutputType>[]
        }
        count: {
          args: Prisma.FeaturedItemsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FeaturedItemsCountAggregateOutputType> | number
        }
      }
    }
    IncludedItems: {
      payload: Prisma.$IncludedItemsPayload<ExtArgs>
      fields: Prisma.IncludedItemsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IncludedItemsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IncludedItemsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>
        }
        findFirst: {
          args: Prisma.IncludedItemsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IncludedItemsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>
        }
        findMany: {
          args: Prisma.IncludedItemsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>[]
        }
        create: {
          args: Prisma.IncludedItemsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>
        }
        createMany: {
          args: Prisma.IncludedItemsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IncludedItemsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>[]
        }
        delete: {
          args: Prisma.IncludedItemsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>
        }
        update: {
          args: Prisma.IncludedItemsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>
        }
        deleteMany: {
          args: Prisma.IncludedItemsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IncludedItemsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IncludedItemsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>[]
        }
        upsert: {
          args: Prisma.IncludedItemsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncludedItemsPayload>
        }
        aggregate: {
          args: Prisma.IncludedItemsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIncludedItems>
        }
        groupBy: {
          args: Prisma.IncludedItemsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IncludedItemsGroupByOutputType>[]
        }
        count: {
          args: Prisma.IncludedItemsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IncludedItemsCountAggregateOutputType> | number
        }
      }
    }
    ExcludedItems: {
      payload: Prisma.$ExcludedItemsPayload<ExtArgs>
      fields: Prisma.ExcludedItemsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ExcludedItemsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ExcludedItemsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>
        }
        findFirst: {
          args: Prisma.ExcludedItemsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ExcludedItemsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>
        }
        findMany: {
          args: Prisma.ExcludedItemsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>[]
        }
        create: {
          args: Prisma.ExcludedItemsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>
        }
        createMany: {
          args: Prisma.ExcludedItemsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ExcludedItemsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>[]
        }
        delete: {
          args: Prisma.ExcludedItemsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>
        }
        update: {
          args: Prisma.ExcludedItemsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>
        }
        deleteMany: {
          args: Prisma.ExcludedItemsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ExcludedItemsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ExcludedItemsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>[]
        }
        upsert: {
          args: Prisma.ExcludedItemsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExcludedItemsPayload>
        }
        aggregate: {
          args: Prisma.ExcludedItemsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExcludedItems>
        }
        groupBy: {
          args: Prisma.ExcludedItemsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExcludedItemsGroupByOutputType>[]
        }
        count: {
          args: Prisma.ExcludedItemsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExcludedItemsCountAggregateOutputType> | number
        }
      }
    }
    Blogs: {
      payload: Prisma.$BlogsPayload<ExtArgs>
      fields: Prisma.BlogsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BlogsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BlogsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>
        }
        findFirst: {
          args: Prisma.BlogsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BlogsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>
        }
        findMany: {
          args: Prisma.BlogsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>[]
        }
        create: {
          args: Prisma.BlogsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>
        }
        createMany: {
          args: Prisma.BlogsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BlogsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>[]
        }
        delete: {
          args: Prisma.BlogsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>
        }
        update: {
          args: Prisma.BlogsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>
        }
        deleteMany: {
          args: Prisma.BlogsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BlogsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BlogsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>[]
        }
        upsert: {
          args: Prisma.BlogsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogsPayload>
        }
        aggregate: {
          args: Prisma.BlogsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlogs>
        }
        groupBy: {
          args: Prisma.BlogsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogsGroupByOutputType>[]
        }
        count: {
          args: Prisma.BlogsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogsCountAggregateOutputType> | number
        }
      }
    }
    BlogImages: {
      payload: Prisma.$BlogImagesPayload<ExtArgs>
      fields: Prisma.BlogImagesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BlogImagesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BlogImagesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>
        }
        findFirst: {
          args: Prisma.BlogImagesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BlogImagesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>
        }
        findMany: {
          args: Prisma.BlogImagesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>[]
        }
        create: {
          args: Prisma.BlogImagesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>
        }
        createMany: {
          args: Prisma.BlogImagesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BlogImagesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>[]
        }
        delete: {
          args: Prisma.BlogImagesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>
        }
        update: {
          args: Prisma.BlogImagesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>
        }
        deleteMany: {
          args: Prisma.BlogImagesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BlogImagesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BlogImagesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>[]
        }
        upsert: {
          args: Prisma.BlogImagesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogImagesPayload>
        }
        aggregate: {
          args: Prisma.BlogImagesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlogImages>
        }
        groupBy: {
          args: Prisma.BlogImagesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogImagesGroupByOutputType>[]
        }
        count: {
          args: Prisma.BlogImagesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogImagesCountAggregateOutputType> | number
        }
      }
    }
    BlogCategory: {
      payload: Prisma.$BlogCategoryPayload<ExtArgs>
      fields: Prisma.BlogCategoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BlogCategoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BlogCategoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>
        }
        findFirst: {
          args: Prisma.BlogCategoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BlogCategoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>
        }
        findMany: {
          args: Prisma.BlogCategoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>[]
        }
        create: {
          args: Prisma.BlogCategoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>
        }
        createMany: {
          args: Prisma.BlogCategoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BlogCategoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>[]
        }
        delete: {
          args: Prisma.BlogCategoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>
        }
        update: {
          args: Prisma.BlogCategoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>
        }
        deleteMany: {
          args: Prisma.BlogCategoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BlogCategoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BlogCategoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>[]
        }
        upsert: {
          args: Prisma.BlogCategoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogCategoryPayload>
        }
        aggregate: {
          args: Prisma.BlogCategoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlogCategory>
        }
        groupBy: {
          args: Prisma.BlogCategoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogCategoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.BlogCategoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogCategoryCountAggregateOutputType> | number
        }
      }
    }
    Destinations: {
      payload: Prisma.$DestinationsPayload<ExtArgs>
      fields: Prisma.DestinationsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DestinationsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DestinationsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>
        }
        findFirst: {
          args: Prisma.DestinationsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DestinationsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>
        }
        findMany: {
          args: Prisma.DestinationsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>[]
        }
        create: {
          args: Prisma.DestinationsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>
        }
        createMany: {
          args: Prisma.DestinationsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DestinationsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>[]
        }
        delete: {
          args: Prisma.DestinationsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>
        }
        update: {
          args: Prisma.DestinationsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>
        }
        deleteMany: {
          args: Prisma.DestinationsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DestinationsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DestinationsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>[]
        }
        upsert: {
          args: Prisma.DestinationsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationsPayload>
        }
        aggregate: {
          args: Prisma.DestinationsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDestinations>
        }
        groupBy: {
          args: Prisma.DestinationsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DestinationsGroupByOutputType>[]
        }
        count: {
          args: Prisma.DestinationsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DestinationsCountAggregateOutputType> | number
        }
      }
    }
    DestinationFAQ: {
      payload: Prisma.$DestinationFAQPayload<ExtArgs>
      fields: Prisma.DestinationFAQFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DestinationFAQFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DestinationFAQFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>
        }
        findFirst: {
          args: Prisma.DestinationFAQFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DestinationFAQFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>
        }
        findMany: {
          args: Prisma.DestinationFAQFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>[]
        }
        create: {
          args: Prisma.DestinationFAQCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>
        }
        createMany: {
          args: Prisma.DestinationFAQCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DestinationFAQCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>[]
        }
        delete: {
          args: Prisma.DestinationFAQDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>
        }
        update: {
          args: Prisma.DestinationFAQUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>
        }
        deleteMany: {
          args: Prisma.DestinationFAQDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DestinationFAQUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DestinationFAQUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>[]
        }
        upsert: {
          args: Prisma.DestinationFAQUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DestinationFAQPayload>
        }
        aggregate: {
          args: Prisma.DestinationFAQAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDestinationFAQ>
        }
        groupBy: {
          args: Prisma.DestinationFAQGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DestinationFAQGroupByOutputType>[]
        }
        count: {
          args: Prisma.DestinationFAQCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DestinationFAQCountAggregateOutputType> | number
        }
      }
    }
    Testimonials: {
      payload: Prisma.$TestimonialsPayload<ExtArgs>
      fields: Prisma.TestimonialsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TestimonialsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TestimonialsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>
        }
        findFirst: {
          args: Prisma.TestimonialsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TestimonialsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>
        }
        findMany: {
          args: Prisma.TestimonialsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>[]
        }
        create: {
          args: Prisma.TestimonialsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>
        }
        createMany: {
          args: Prisma.TestimonialsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TestimonialsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>[]
        }
        delete: {
          args: Prisma.TestimonialsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>
        }
        update: {
          args: Prisma.TestimonialsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>
        }
        deleteMany: {
          args: Prisma.TestimonialsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TestimonialsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TestimonialsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>[]
        }
        upsert: {
          args: Prisma.TestimonialsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialsPayload>
        }
        aggregate: {
          args: Prisma.TestimonialsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTestimonials>
        }
        groupBy: {
          args: Prisma.TestimonialsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TestimonialsGroupByOutputType>[]
        }
        count: {
          args: Prisma.TestimonialsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TestimonialsCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const PackageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  days: 'days',
  nights: 'nights',
  image: 'image',
  price: 'price',
  type: 'type',
  location: 'location',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PackageScalarFieldEnum = (typeof PackageScalarFieldEnum)[keyof typeof PackageScalarFieldEnum]


export const BookingsScalarFieldEnum = {
  id: 'id',
  customerName: 'customerName',
  customerEmail: 'customerEmail',
  customerPhone: 'customerPhone',
  numberOfPeople: 'numberOfPeople',
  paid: 'paid',
  packageId: 'packageId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BookingsScalarFieldEnum = (typeof BookingsScalarFieldEnum)[keyof typeof BookingsScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  paid: 'paid',
  paymentMethod: 'paymentMethod',
  razorpayPaymentId: 'razorpayPaymentId',
  paymentDate: 'paymentDate',
  bookingId: 'bookingId',
  createdAt: 'createdAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const DayItineraryScalarFieldEnum = {
  id: 'id',
  dayNumber: 'dayNumber',
  description: 'description',
  packageId: 'packageId'
} as const

export type DayItineraryScalarFieldEnum = (typeof DayItineraryScalarFieldEnum)[keyof typeof DayItineraryScalarFieldEnum]


export const FeaturedItemsScalarFieldEnum = {
  id: 'id',
  item: 'item',
  dayItineraryId: 'dayItineraryId'
} as const

export type FeaturedItemsScalarFieldEnum = (typeof FeaturedItemsScalarFieldEnum)[keyof typeof FeaturedItemsScalarFieldEnum]


export const IncludedItemsScalarFieldEnum = {
  id: 'id',
  item: 'item',
  packageId: 'packageId'
} as const

export type IncludedItemsScalarFieldEnum = (typeof IncludedItemsScalarFieldEnum)[keyof typeof IncludedItemsScalarFieldEnum]


export const ExcludedItemsScalarFieldEnum = {
  id: 'id',
  item: 'item',
  packageId: 'packageId'
} as const

export type ExcludedItemsScalarFieldEnum = (typeof ExcludedItemsScalarFieldEnum)[keyof typeof ExcludedItemsScalarFieldEnum]


export const BlogsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  html: 'html',
  thumbnail: 'thumbnail',
  customerName: 'customerName',
  feedback: 'feedback',
  author: 'author',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BlogsScalarFieldEnum = (typeof BlogsScalarFieldEnum)[keyof typeof BlogsScalarFieldEnum]


export const BlogImagesScalarFieldEnum = {
  id: 'id',
  url: 'url',
  blogId: 'blogId'
} as const

export type BlogImagesScalarFieldEnum = (typeof BlogImagesScalarFieldEnum)[keyof typeof BlogImagesScalarFieldEnum]


export const BlogCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type BlogCategoryScalarFieldEnum = (typeof BlogCategoryScalarFieldEnum)[keyof typeof BlogCategoryScalarFieldEnum]


export const DestinationsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tag: 'tag',
  title: 'title',
  description: 'description',
  image: 'image',
  country: 'country',
  visa: 'visa',
  languagesSpoken: 'languagesSpoken',
  currency: 'currency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DestinationsScalarFieldEnum = (typeof DestinationsScalarFieldEnum)[keyof typeof DestinationsScalarFieldEnum]


export const DestinationFAQScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  destinationId: 'destinationId'
} as const

export type DestinationFAQScalarFieldEnum = (typeof DestinationFAQScalarFieldEnum)[keyof typeof DestinationFAQScalarFieldEnum]


export const TestimonialsScalarFieldEnum = {
  id: 'id',
  customerName: 'customerName',
  feedback: 'feedback',
  rating: 'rating',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TestimonialsScalarFieldEnum = (typeof TestimonialsScalarFieldEnum)[keyof typeof TestimonialsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  package?: Prisma.PackageOmit
  bookings?: Prisma.BookingsOmit
  payment?: Prisma.PaymentOmit
  dayItinerary?: Prisma.DayItineraryOmit
  featuredItems?: Prisma.FeaturedItemsOmit
  includedItems?: Prisma.IncludedItemsOmit
  excludedItems?: Prisma.ExcludedItemsOmit
  blogs?: Prisma.BlogsOmit
  blogImages?: Prisma.BlogImagesOmit
  blogCategory?: Prisma.BlogCategoryOmit
  destinations?: Prisma.DestinationsOmit
  destinationFAQ?: Prisma.DestinationFAQOmit
  testimonials?: Prisma.TestimonialsOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

