
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `BlogImages` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BlogImages
 * 
 */
export type BlogImagesModel = runtime.Types.Result.DefaultSelection<Prisma.$BlogImagesPayload>

export type AggregateBlogImages = {
  _count: BlogImagesCountAggregateOutputType | null
  _min: BlogImagesMinAggregateOutputType | null
  _max: BlogImagesMaxAggregateOutputType | null
}

export type BlogImagesMinAggregateOutputType = {
  id: string | null
  url: string | null
  blogId: string | null
}

export type BlogImagesMaxAggregateOutputType = {
  id: string | null
  url: string | null
  blogId: string | null
}

export type BlogImagesCountAggregateOutputType = {
  id: number
  url: number
  blogId: number
  _all: number
}


export type BlogImagesMinAggregateInputType = {
  id?: true
  url?: true
  blogId?: true
}

export type BlogImagesMaxAggregateInputType = {
  id?: true
  url?: true
  blogId?: true
}

export type BlogImagesCountAggregateInputType = {
  id?: true
  url?: true
  blogId?: true
  _all?: true
}

export type BlogImagesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BlogImages to aggregate.
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogImages to fetch.
   */
  orderBy?: Prisma.BlogImagesOrderByWithRelationInput | Prisma.BlogImagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BlogImagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BlogImages
  **/
  _count?: true | BlogImagesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BlogImagesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BlogImagesMaxAggregateInputType
}

export type GetBlogImagesAggregateType<T extends BlogImagesAggregateArgs> = {
      [P in keyof T & keyof AggregateBlogImages]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBlogImages[P]>
    : Prisma.GetScalarType<T[P], AggregateBlogImages[P]>
}




export type BlogImagesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BlogImagesWhereInput
  orderBy?: Prisma.BlogImagesOrderByWithAggregationInput | Prisma.BlogImagesOrderByWithAggregationInput[]
  by: Prisma.BlogImagesScalarFieldEnum[] | Prisma.BlogImagesScalarFieldEnum
  having?: Prisma.BlogImagesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BlogImagesCountAggregateInputType | true
  _min?: BlogImagesMinAggregateInputType
  _max?: BlogImagesMaxAggregateInputType
}

export type BlogImagesGroupByOutputType = {
  id: string
  url: string
  blogId: string
  _count: BlogImagesCountAggregateOutputType | null
  _min: BlogImagesMinAggregateOutputType | null
  _max: BlogImagesMaxAggregateOutputType | null
}

type GetBlogImagesGroupByPayload<T extends BlogImagesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BlogImagesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BlogImagesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BlogImagesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BlogImagesGroupByOutputType[P]>
      }
    >
  >



export type BlogImagesWhereInput = {
  AND?: Prisma.BlogImagesWhereInput | Prisma.BlogImagesWhereInput[]
  OR?: Prisma.BlogImagesWhereInput[]
  NOT?: Prisma.BlogImagesWhereInput | Prisma.BlogImagesWhereInput[]
  id?: Prisma.StringFilter<"BlogImages"> | string
  url?: Prisma.StringFilter<"BlogImages"> | string
  blogId?: Prisma.StringFilter<"BlogImages"> | string
  blog?: Prisma.XOR<Prisma.BlogsScalarRelationFilter, Prisma.BlogsWhereInput>
}

export type BlogImagesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  blogId?: Prisma.SortOrder
  blog?: Prisma.BlogsOrderByWithRelationInput
}

export type BlogImagesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BlogImagesWhereInput | Prisma.BlogImagesWhereInput[]
  OR?: Prisma.BlogImagesWhereInput[]
  NOT?: Prisma.BlogImagesWhereInput | Prisma.BlogImagesWhereInput[]
  url?: Prisma.StringFilter<"BlogImages"> | string
  blogId?: Prisma.StringFilter<"BlogImages"> | string
  blog?: Prisma.XOR<Prisma.BlogsScalarRelationFilter, Prisma.BlogsWhereInput>
}, "id">

export type BlogImagesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  blogId?: Prisma.SortOrder
  _count?: Prisma.BlogImagesCountOrderByAggregateInput
  _max?: Prisma.BlogImagesMaxOrderByAggregateInput
  _min?: Prisma.BlogImagesMinOrderByAggregateInput
}

export type BlogImagesScalarWhereWithAggregatesInput = {
  AND?: Prisma.BlogImagesScalarWhereWithAggregatesInput | Prisma.BlogImagesScalarWhereWithAggregatesInput[]
  OR?: Prisma.BlogImagesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BlogImagesScalarWhereWithAggregatesInput | Prisma.BlogImagesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BlogImages"> | string
  url?: Prisma.StringWithAggregatesFilter<"BlogImages"> | string
  blogId?: Prisma.StringWithAggregatesFilter<"BlogImages"> | string
}

export type BlogImagesCreateInput = {
  id?: string
  url: string
  blog: Prisma.BlogsCreateNestedOneWithoutImagesInput
}

export type BlogImagesUncheckedCreateInput = {
  id?: string
  url: string
  blogId: string
}

export type BlogImagesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  blog?: Prisma.BlogsUpdateOneRequiredWithoutImagesNestedInput
}

export type BlogImagesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  blogId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BlogImagesCreateManyInput = {
  id?: string
  url: string
  blogId: string
}

export type BlogImagesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BlogImagesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  blogId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BlogImagesListRelationFilter = {
  every?: Prisma.BlogImagesWhereInput
  some?: Prisma.BlogImagesWhereInput
  none?: Prisma.BlogImagesWhereInput
}

export type BlogImagesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BlogImagesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  blogId?: Prisma.SortOrder
}

export type BlogImagesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  blogId?: Prisma.SortOrder
}

export type BlogImagesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  blogId?: Prisma.SortOrder
}

export type BlogImagesCreateNestedManyWithoutBlogInput = {
  create?: Prisma.XOR<Prisma.BlogImagesCreateWithoutBlogInput, Prisma.BlogImagesUncheckedCreateWithoutBlogInput> | Prisma.BlogImagesCreateWithoutBlogInput[] | Prisma.BlogImagesUncheckedCreateWithoutBlogInput[]
  connectOrCreate?: Prisma.BlogImagesCreateOrConnectWithoutBlogInput | Prisma.BlogImagesCreateOrConnectWithoutBlogInput[]
  createMany?: Prisma.BlogImagesCreateManyBlogInputEnvelope
  connect?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
}

export type BlogImagesUncheckedCreateNestedManyWithoutBlogInput = {
  create?: Prisma.XOR<Prisma.BlogImagesCreateWithoutBlogInput, Prisma.BlogImagesUncheckedCreateWithoutBlogInput> | Prisma.BlogImagesCreateWithoutBlogInput[] | Prisma.BlogImagesUncheckedCreateWithoutBlogInput[]
  connectOrCreate?: Prisma.BlogImagesCreateOrConnectWithoutBlogInput | Prisma.BlogImagesCreateOrConnectWithoutBlogInput[]
  createMany?: Prisma.BlogImagesCreateManyBlogInputEnvelope
  connect?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
}

export type BlogImagesUpdateManyWithoutBlogNestedInput = {
  create?: Prisma.XOR<Prisma.BlogImagesCreateWithoutBlogInput, Prisma.BlogImagesUncheckedCreateWithoutBlogInput> | Prisma.BlogImagesCreateWithoutBlogInput[] | Prisma.BlogImagesUncheckedCreateWithoutBlogInput[]
  connectOrCreate?: Prisma.BlogImagesCreateOrConnectWithoutBlogInput | Prisma.BlogImagesCreateOrConnectWithoutBlogInput[]
  upsert?: Prisma.BlogImagesUpsertWithWhereUniqueWithoutBlogInput | Prisma.BlogImagesUpsertWithWhereUniqueWithoutBlogInput[]
  createMany?: Prisma.BlogImagesCreateManyBlogInputEnvelope
  set?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  disconnect?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  delete?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  connect?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  update?: Prisma.BlogImagesUpdateWithWhereUniqueWithoutBlogInput | Prisma.BlogImagesUpdateWithWhereUniqueWithoutBlogInput[]
  updateMany?: Prisma.BlogImagesUpdateManyWithWhereWithoutBlogInput | Prisma.BlogImagesUpdateManyWithWhereWithoutBlogInput[]
  deleteMany?: Prisma.BlogImagesScalarWhereInput | Prisma.BlogImagesScalarWhereInput[]
}

export type BlogImagesUncheckedUpdateManyWithoutBlogNestedInput = {
  create?: Prisma.XOR<Prisma.BlogImagesCreateWithoutBlogInput, Prisma.BlogImagesUncheckedCreateWithoutBlogInput> | Prisma.BlogImagesCreateWithoutBlogInput[] | Prisma.BlogImagesUncheckedCreateWithoutBlogInput[]
  connectOrCreate?: Prisma.BlogImagesCreateOrConnectWithoutBlogInput | Prisma.BlogImagesCreateOrConnectWithoutBlogInput[]
  upsert?: Prisma.BlogImagesUpsertWithWhereUniqueWithoutBlogInput | Prisma.BlogImagesUpsertWithWhereUniqueWithoutBlogInput[]
  createMany?: Prisma.BlogImagesCreateManyBlogInputEnvelope
  set?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  disconnect?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  delete?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  connect?: Prisma.BlogImagesWhereUniqueInput | Prisma.BlogImagesWhereUniqueInput[]
  update?: Prisma.BlogImagesUpdateWithWhereUniqueWithoutBlogInput | Prisma.BlogImagesUpdateWithWhereUniqueWithoutBlogInput[]
  updateMany?: Prisma.BlogImagesUpdateManyWithWhereWithoutBlogInput | Prisma.BlogImagesUpdateManyWithWhereWithoutBlogInput[]
  deleteMany?: Prisma.BlogImagesScalarWhereInput | Prisma.BlogImagesScalarWhereInput[]
}

export type BlogImagesCreateWithoutBlogInput = {
  id?: string
  url: string
}

export type BlogImagesUncheckedCreateWithoutBlogInput = {
  id?: string
  url: string
}

export type BlogImagesCreateOrConnectWithoutBlogInput = {
  where: Prisma.BlogImagesWhereUniqueInput
  create: Prisma.XOR<Prisma.BlogImagesCreateWithoutBlogInput, Prisma.BlogImagesUncheckedCreateWithoutBlogInput>
}

export type BlogImagesCreateManyBlogInputEnvelope = {
  data: Prisma.BlogImagesCreateManyBlogInput | Prisma.BlogImagesCreateManyBlogInput[]
  skipDuplicates?: boolean
}

export type BlogImagesUpsertWithWhereUniqueWithoutBlogInput = {
  where: Prisma.BlogImagesWhereUniqueInput
  update: Prisma.XOR<Prisma.BlogImagesUpdateWithoutBlogInput, Prisma.BlogImagesUncheckedUpdateWithoutBlogInput>
  create: Prisma.XOR<Prisma.BlogImagesCreateWithoutBlogInput, Prisma.BlogImagesUncheckedCreateWithoutBlogInput>
}

export type BlogImagesUpdateWithWhereUniqueWithoutBlogInput = {
  where: Prisma.BlogImagesWhereUniqueInput
  data: Prisma.XOR<Prisma.BlogImagesUpdateWithoutBlogInput, Prisma.BlogImagesUncheckedUpdateWithoutBlogInput>
}

export type BlogImagesUpdateManyWithWhereWithoutBlogInput = {
  where: Prisma.BlogImagesScalarWhereInput
  data: Prisma.XOR<Prisma.BlogImagesUpdateManyMutationInput, Prisma.BlogImagesUncheckedUpdateManyWithoutBlogInput>
}

export type BlogImagesScalarWhereInput = {
  AND?: Prisma.BlogImagesScalarWhereInput | Prisma.BlogImagesScalarWhereInput[]
  OR?: Prisma.BlogImagesScalarWhereInput[]
  NOT?: Prisma.BlogImagesScalarWhereInput | Prisma.BlogImagesScalarWhereInput[]
  id?: Prisma.StringFilter<"BlogImages"> | string
  url?: Prisma.StringFilter<"BlogImages"> | string
  blogId?: Prisma.StringFilter<"BlogImages"> | string
}

export type BlogImagesCreateManyBlogInput = {
  id?: string
  url: string
}

export type BlogImagesUpdateWithoutBlogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BlogImagesUncheckedUpdateWithoutBlogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BlogImagesUncheckedUpdateManyWithoutBlogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}



export type BlogImagesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  blogId?: boolean
  blog?: boolean | Prisma.BlogsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["blogImages"]>

export type BlogImagesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  blogId?: boolean
  blog?: boolean | Prisma.BlogsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["blogImages"]>

export type BlogImagesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  blogId?: boolean
  blog?: boolean | Prisma.BlogsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["blogImages"]>

export type BlogImagesSelectScalar = {
  id?: boolean
  url?: boolean
  blogId?: boolean
}

export type BlogImagesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "url" | "blogId", ExtArgs["result"]["blogImages"]>
export type BlogImagesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  blog?: boolean | Prisma.BlogsDefaultArgs<ExtArgs>
}
export type BlogImagesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  blog?: boolean | Prisma.BlogsDefaultArgs<ExtArgs>
}
export type BlogImagesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  blog?: boolean | Prisma.BlogsDefaultArgs<ExtArgs>
}

export type $BlogImagesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BlogImages"
  objects: {
    blog: Prisma.$BlogsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    url: string
    blogId: string
  }, ExtArgs["result"]["blogImages"]>
  composites: {}
}

export type BlogImagesGetPayload<S extends boolean | null | undefined | BlogImagesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload, S>

export type BlogImagesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BlogImagesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BlogImagesCountAggregateInputType | true
  }

export interface BlogImagesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BlogImages'], meta: { name: 'BlogImages' } }
  /**
   * Find zero or one BlogImages that matches the filter.
   * @param {BlogImagesFindUniqueArgs} args - Arguments to find a BlogImages
   * @example
   * // Get one BlogImages
   * const blogImages = await prisma.blogImages.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BlogImagesFindUniqueArgs>(args: Prisma.SelectSubset<T, BlogImagesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BlogImages that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BlogImagesFindUniqueOrThrowArgs} args - Arguments to find a BlogImages
   * @example
   * // Get one BlogImages
   * const blogImages = await prisma.blogImages.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BlogImagesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BlogImagesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BlogImages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesFindFirstArgs} args - Arguments to find a BlogImages
   * @example
   * // Get one BlogImages
   * const blogImages = await prisma.blogImages.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BlogImagesFindFirstArgs>(args?: Prisma.SelectSubset<T, BlogImagesFindFirstArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BlogImages that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesFindFirstOrThrowArgs} args - Arguments to find a BlogImages
   * @example
   * // Get one BlogImages
   * const blogImages = await prisma.blogImages.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BlogImagesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BlogImagesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BlogImages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BlogImages
   * const blogImages = await prisma.blogImages.findMany()
   * 
   * // Get first 10 BlogImages
   * const blogImages = await prisma.blogImages.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const blogImagesWithIdOnly = await prisma.blogImages.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BlogImagesFindManyArgs>(args?: Prisma.SelectSubset<T, BlogImagesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BlogImages.
   * @param {BlogImagesCreateArgs} args - Arguments to create a BlogImages.
   * @example
   * // Create one BlogImages
   * const BlogImages = await prisma.blogImages.create({
   *   data: {
   *     // ... data to create a BlogImages
   *   }
   * })
   * 
   */
  create<T extends BlogImagesCreateArgs>(args: Prisma.SelectSubset<T, BlogImagesCreateArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BlogImages.
   * @param {BlogImagesCreateManyArgs} args - Arguments to create many BlogImages.
   * @example
   * // Create many BlogImages
   * const blogImages = await prisma.blogImages.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BlogImagesCreateManyArgs>(args?: Prisma.SelectSubset<T, BlogImagesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BlogImages and returns the data saved in the database.
   * @param {BlogImagesCreateManyAndReturnArgs} args - Arguments to create many BlogImages.
   * @example
   * // Create many BlogImages
   * const blogImages = await prisma.blogImages.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BlogImages and only return the `id`
   * const blogImagesWithIdOnly = await prisma.blogImages.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BlogImagesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BlogImagesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BlogImages.
   * @param {BlogImagesDeleteArgs} args - Arguments to delete one BlogImages.
   * @example
   * // Delete one BlogImages
   * const BlogImages = await prisma.blogImages.delete({
   *   where: {
   *     // ... filter to delete one BlogImages
   *   }
   * })
   * 
   */
  delete<T extends BlogImagesDeleteArgs>(args: Prisma.SelectSubset<T, BlogImagesDeleteArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BlogImages.
   * @param {BlogImagesUpdateArgs} args - Arguments to update one BlogImages.
   * @example
   * // Update one BlogImages
   * const blogImages = await prisma.blogImages.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BlogImagesUpdateArgs>(args: Prisma.SelectSubset<T, BlogImagesUpdateArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BlogImages.
   * @param {BlogImagesDeleteManyArgs} args - Arguments to filter BlogImages to delete.
   * @example
   * // Delete a few BlogImages
   * const { count } = await prisma.blogImages.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BlogImagesDeleteManyArgs>(args?: Prisma.SelectSubset<T, BlogImagesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BlogImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BlogImages
   * const blogImages = await prisma.blogImages.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BlogImagesUpdateManyArgs>(args: Prisma.SelectSubset<T, BlogImagesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BlogImages and returns the data updated in the database.
   * @param {BlogImagesUpdateManyAndReturnArgs} args - Arguments to update many BlogImages.
   * @example
   * // Update many BlogImages
   * const blogImages = await prisma.blogImages.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BlogImages and only return the `id`
   * const blogImagesWithIdOnly = await prisma.blogImages.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BlogImagesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BlogImagesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BlogImages.
   * @param {BlogImagesUpsertArgs} args - Arguments to update or create a BlogImages.
   * @example
   * // Update or create a BlogImages
   * const blogImages = await prisma.blogImages.upsert({
   *   create: {
   *     // ... data to create a BlogImages
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BlogImages we want to update
   *   }
   * })
   */
  upsert<T extends BlogImagesUpsertArgs>(args: Prisma.SelectSubset<T, BlogImagesUpsertArgs<ExtArgs>>): Prisma.Prisma__BlogImagesClient<runtime.Types.Result.GetResult<Prisma.$BlogImagesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BlogImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesCountArgs} args - Arguments to filter BlogImages to count.
   * @example
   * // Count the number of BlogImages
   * const count = await prisma.blogImages.count({
   *   where: {
   *     // ... the filter for the BlogImages we want to count
   *   }
   * })
  **/
  count<T extends BlogImagesCountArgs>(
    args?: Prisma.Subset<T, BlogImagesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BlogImagesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BlogImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BlogImagesAggregateArgs>(args: Prisma.Subset<T, BlogImagesAggregateArgs>): Prisma.PrismaPromise<GetBlogImagesAggregateType<T>>

  /**
   * Group by BlogImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogImagesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BlogImagesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BlogImagesGroupByArgs['orderBy'] }
      : { orderBy?: BlogImagesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BlogImagesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBlogImagesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BlogImages model
 */
readonly fields: BlogImagesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BlogImages.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BlogImagesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  blog<T extends Prisma.BlogsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BlogsDefaultArgs<ExtArgs>>): Prisma.Prisma__BlogsClient<runtime.Types.Result.GetResult<Prisma.$BlogsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BlogImages model
 */
export interface BlogImagesFieldRefs {
  readonly id: Prisma.FieldRef<"BlogImages", 'String'>
  readonly url: Prisma.FieldRef<"BlogImages", 'String'>
  readonly blogId: Prisma.FieldRef<"BlogImages", 'String'>
}
    

// Custom InputTypes
/**
 * BlogImages findUnique
 */
export type BlogImagesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * Filter, which BlogImages to fetch.
   */
  where: Prisma.BlogImagesWhereUniqueInput
}

/**
 * BlogImages findUniqueOrThrow
 */
export type BlogImagesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * Filter, which BlogImages to fetch.
   */
  where: Prisma.BlogImagesWhereUniqueInput
}

/**
 * BlogImages findFirst
 */
export type BlogImagesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * Filter, which BlogImages to fetch.
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogImages to fetch.
   */
  orderBy?: Prisma.BlogImagesOrderByWithRelationInput | Prisma.BlogImagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BlogImages.
   */
  cursor?: Prisma.BlogImagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlogImages.
   */
  distinct?: Prisma.BlogImagesScalarFieldEnum | Prisma.BlogImagesScalarFieldEnum[]
}

/**
 * BlogImages findFirstOrThrow
 */
export type BlogImagesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * Filter, which BlogImages to fetch.
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogImages to fetch.
   */
  orderBy?: Prisma.BlogImagesOrderByWithRelationInput | Prisma.BlogImagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BlogImages.
   */
  cursor?: Prisma.BlogImagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlogImages.
   */
  distinct?: Prisma.BlogImagesScalarFieldEnum | Prisma.BlogImagesScalarFieldEnum[]
}

/**
 * BlogImages findMany
 */
export type BlogImagesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * Filter, which BlogImages to fetch.
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogImages to fetch.
   */
  orderBy?: Prisma.BlogImagesOrderByWithRelationInput | Prisma.BlogImagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BlogImages.
   */
  cursor?: Prisma.BlogImagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogImages.
   */
  skip?: number
  distinct?: Prisma.BlogImagesScalarFieldEnum | Prisma.BlogImagesScalarFieldEnum[]
}

/**
 * BlogImages create
 */
export type BlogImagesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * The data needed to create a BlogImages.
   */
  data: Prisma.XOR<Prisma.BlogImagesCreateInput, Prisma.BlogImagesUncheckedCreateInput>
}

/**
 * BlogImages createMany
 */
export type BlogImagesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BlogImages.
   */
  data: Prisma.BlogImagesCreateManyInput | Prisma.BlogImagesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BlogImages createManyAndReturn
 */
export type BlogImagesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * The data used to create many BlogImages.
   */
  data: Prisma.BlogImagesCreateManyInput | Prisma.BlogImagesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BlogImages update
 */
export type BlogImagesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * The data needed to update a BlogImages.
   */
  data: Prisma.XOR<Prisma.BlogImagesUpdateInput, Prisma.BlogImagesUncheckedUpdateInput>
  /**
   * Choose, which BlogImages to update.
   */
  where: Prisma.BlogImagesWhereUniqueInput
}

/**
 * BlogImages updateMany
 */
export type BlogImagesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BlogImages.
   */
  data: Prisma.XOR<Prisma.BlogImagesUpdateManyMutationInput, Prisma.BlogImagesUncheckedUpdateManyInput>
  /**
   * Filter which BlogImages to update
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * Limit how many BlogImages to update.
   */
  limit?: number
}

/**
 * BlogImages updateManyAndReturn
 */
export type BlogImagesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * The data used to update BlogImages.
   */
  data: Prisma.XOR<Prisma.BlogImagesUpdateManyMutationInput, Prisma.BlogImagesUncheckedUpdateManyInput>
  /**
   * Filter which BlogImages to update
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * Limit how many BlogImages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BlogImages upsert
 */
export type BlogImagesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * The filter to search for the BlogImages to update in case it exists.
   */
  where: Prisma.BlogImagesWhereUniqueInput
  /**
   * In case the BlogImages found by the `where` argument doesn't exist, create a new BlogImages with this data.
   */
  create: Prisma.XOR<Prisma.BlogImagesCreateInput, Prisma.BlogImagesUncheckedCreateInput>
  /**
   * In case the BlogImages was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BlogImagesUpdateInput, Prisma.BlogImagesUncheckedUpdateInput>
}

/**
 * BlogImages delete
 */
export type BlogImagesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
  /**
   * Filter which BlogImages to delete.
   */
  where: Prisma.BlogImagesWhereUniqueInput
}

/**
 * BlogImages deleteMany
 */
export type BlogImagesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BlogImages to delete
   */
  where?: Prisma.BlogImagesWhereInput
  /**
   * Limit how many BlogImages to delete.
   */
  limit?: number
}

/**
 * BlogImages without action
 */
export type BlogImagesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogImages
   */
  select?: Prisma.BlogImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogImages
   */
  omit?: Prisma.BlogImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogImagesInclude<ExtArgs> | null
}
