
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `DayItinerary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DayItinerary
 * 
 */
export type DayItineraryModel = runtime.Types.Result.DefaultSelection<Prisma.$DayItineraryPayload>

export type AggregateDayItinerary = {
  _count: DayItineraryCountAggregateOutputType | null
  _avg: DayItineraryAvgAggregateOutputType | null
  _sum: DayItinerarySumAggregateOutputType | null
  _min: DayItineraryMinAggregateOutputType | null
  _max: DayItineraryMaxAggregateOutputType | null
}

export type DayItineraryAvgAggregateOutputType = {
  dayNumber: number | null
}

export type DayItinerarySumAggregateOutputType = {
  dayNumber: number | null
}

export type DayItineraryMinAggregateOutputType = {
  id: string | null
  dayNumber: number | null
  description: string | null
  packageId: string | null
}

export type DayItineraryMaxAggregateOutputType = {
  id: string | null
  dayNumber: number | null
  description: string | null
  packageId: string | null
}

export type DayItineraryCountAggregateOutputType = {
  id: number
  dayNumber: number
  description: number
  packageId: number
  _all: number
}


export type DayItineraryAvgAggregateInputType = {
  dayNumber?: true
}

export type DayItinerarySumAggregateInputType = {
  dayNumber?: true
}

export type DayItineraryMinAggregateInputType = {
  id?: true
  dayNumber?: true
  description?: true
  packageId?: true
}

export type DayItineraryMaxAggregateInputType = {
  id?: true
  dayNumber?: true
  description?: true
  packageId?: true
}

export type DayItineraryCountAggregateInputType = {
  id?: true
  dayNumber?: true
  description?: true
  packageId?: true
  _all?: true
}

export type DayItineraryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DayItinerary to aggregate.
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DayItineraries to fetch.
   */
  orderBy?: Prisma.DayItineraryOrderByWithRelationInput | Prisma.DayItineraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DayItineraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DayItineraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DayItineraries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DayItineraries
  **/
  _count?: true | DayItineraryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DayItineraryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DayItinerarySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DayItineraryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DayItineraryMaxAggregateInputType
}

export type GetDayItineraryAggregateType<T extends DayItineraryAggregateArgs> = {
      [P in keyof T & keyof AggregateDayItinerary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDayItinerary[P]>
    : Prisma.GetScalarType<T[P], AggregateDayItinerary[P]>
}




export type DayItineraryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DayItineraryWhereInput
  orderBy?: Prisma.DayItineraryOrderByWithAggregationInput | Prisma.DayItineraryOrderByWithAggregationInput[]
  by: Prisma.DayItineraryScalarFieldEnum[] | Prisma.DayItineraryScalarFieldEnum
  having?: Prisma.DayItineraryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DayItineraryCountAggregateInputType | true
  _avg?: DayItineraryAvgAggregateInputType
  _sum?: DayItinerarySumAggregateInputType
  _min?: DayItineraryMinAggregateInputType
  _max?: DayItineraryMaxAggregateInputType
}

export type DayItineraryGroupByOutputType = {
  id: string
  dayNumber: number
  description: string
  packageId: string
  _count: DayItineraryCountAggregateOutputType | null
  _avg: DayItineraryAvgAggregateOutputType | null
  _sum: DayItinerarySumAggregateOutputType | null
  _min: DayItineraryMinAggregateOutputType | null
  _max: DayItineraryMaxAggregateOutputType | null
}

type GetDayItineraryGroupByPayload<T extends DayItineraryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DayItineraryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DayItineraryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DayItineraryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DayItineraryGroupByOutputType[P]>
      }
    >
  >



export type DayItineraryWhereInput = {
  AND?: Prisma.DayItineraryWhereInput | Prisma.DayItineraryWhereInput[]
  OR?: Prisma.DayItineraryWhereInput[]
  NOT?: Prisma.DayItineraryWhereInput | Prisma.DayItineraryWhereInput[]
  id?: Prisma.StringFilter<"DayItinerary"> | string
  dayNumber?: Prisma.IntFilter<"DayItinerary"> | number
  description?: Prisma.StringFilter<"DayItinerary"> | string
  packageId?: Prisma.StringFilter<"DayItinerary"> | string
  features?: Prisma.FeaturedItemsListRelationFilter
  package?: Prisma.XOR<Prisma.PackageScalarRelationFilter, Prisma.PackageWhereInput>
}

export type DayItineraryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  description?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
  features?: Prisma.FeaturedItemsOrderByRelationAggregateInput
  package?: Prisma.PackageOrderByWithRelationInput
}

export type DayItineraryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  packageId_dayNumber?: Prisma.DayItineraryPackageIdDayNumberCompoundUniqueInput
  AND?: Prisma.DayItineraryWhereInput | Prisma.DayItineraryWhereInput[]
  OR?: Prisma.DayItineraryWhereInput[]
  NOT?: Prisma.DayItineraryWhereInput | Prisma.DayItineraryWhereInput[]
  dayNumber?: Prisma.IntFilter<"DayItinerary"> | number
  description?: Prisma.StringFilter<"DayItinerary"> | string
  packageId?: Prisma.StringFilter<"DayItinerary"> | string
  features?: Prisma.FeaturedItemsListRelationFilter
  package?: Prisma.XOR<Prisma.PackageScalarRelationFilter, Prisma.PackageWhereInput>
}, "id" | "packageId_dayNumber">

export type DayItineraryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  description?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
  _count?: Prisma.DayItineraryCountOrderByAggregateInput
  _avg?: Prisma.DayItineraryAvgOrderByAggregateInput
  _max?: Prisma.DayItineraryMaxOrderByAggregateInput
  _min?: Prisma.DayItineraryMinOrderByAggregateInput
  _sum?: Prisma.DayItinerarySumOrderByAggregateInput
}

export type DayItineraryScalarWhereWithAggregatesInput = {
  AND?: Prisma.DayItineraryScalarWhereWithAggregatesInput | Prisma.DayItineraryScalarWhereWithAggregatesInput[]
  OR?: Prisma.DayItineraryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DayItineraryScalarWhereWithAggregatesInput | Prisma.DayItineraryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DayItinerary"> | string
  dayNumber?: Prisma.IntWithAggregatesFilter<"DayItinerary"> | number
  description?: Prisma.StringWithAggregatesFilter<"DayItinerary"> | string
  packageId?: Prisma.StringWithAggregatesFilter<"DayItinerary"> | string
}

export type DayItineraryCreateInput = {
  id?: string
  dayNumber: number
  description: string
  features?: Prisma.FeaturedItemsCreateNestedManyWithoutDayItineraryInput
  package: Prisma.PackageCreateNestedOneWithoutItinerariesInput
}

export type DayItineraryUncheckedCreateInput = {
  id?: string
  dayNumber: number
  description: string
  packageId: string
  features?: Prisma.FeaturedItemsUncheckedCreateNestedManyWithoutDayItineraryInput
}

export type DayItineraryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.FeaturedItemsUpdateManyWithoutDayItineraryNestedInput
  package?: Prisma.PackageUpdateOneRequiredWithoutItinerariesNestedInput
}

export type DayItineraryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.FeaturedItemsUncheckedUpdateManyWithoutDayItineraryNestedInput
}

export type DayItineraryCreateManyInput = {
  id?: string
  dayNumber: number
  description: string
  packageId: string
}

export type DayItineraryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DayItineraryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DayItineraryListRelationFilter = {
  every?: Prisma.DayItineraryWhereInput
  some?: Prisma.DayItineraryWhereInput
  none?: Prisma.DayItineraryWhereInput
}

export type DayItineraryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DayItineraryPackageIdDayNumberCompoundUniqueInput = {
  packageId: string
  dayNumber: number
}

export type DayItineraryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  description?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type DayItineraryAvgOrderByAggregateInput = {
  dayNumber?: Prisma.SortOrder
}

export type DayItineraryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  description?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type DayItineraryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dayNumber?: Prisma.SortOrder
  description?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type DayItinerarySumOrderByAggregateInput = {
  dayNumber?: Prisma.SortOrder
}

export type DayItineraryScalarRelationFilter = {
  is?: Prisma.DayItineraryWhereInput
  isNot?: Prisma.DayItineraryWhereInput
}

export type DayItineraryCreateNestedManyWithoutPackageInput = {
  create?: Prisma.XOR<Prisma.DayItineraryCreateWithoutPackageInput, Prisma.DayItineraryUncheckedCreateWithoutPackageInput> | Prisma.DayItineraryCreateWithoutPackageInput[] | Prisma.DayItineraryUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.DayItineraryCreateOrConnectWithoutPackageInput | Prisma.DayItineraryCreateOrConnectWithoutPackageInput[]
  createMany?: Prisma.DayItineraryCreateManyPackageInputEnvelope
  connect?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
}

export type DayItineraryUncheckedCreateNestedManyWithoutPackageInput = {
  create?: Prisma.XOR<Prisma.DayItineraryCreateWithoutPackageInput, Prisma.DayItineraryUncheckedCreateWithoutPackageInput> | Prisma.DayItineraryCreateWithoutPackageInput[] | Prisma.DayItineraryUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.DayItineraryCreateOrConnectWithoutPackageInput | Prisma.DayItineraryCreateOrConnectWithoutPackageInput[]
  createMany?: Prisma.DayItineraryCreateManyPackageInputEnvelope
  connect?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
}

export type DayItineraryUpdateManyWithoutPackageNestedInput = {
  create?: Prisma.XOR<Prisma.DayItineraryCreateWithoutPackageInput, Prisma.DayItineraryUncheckedCreateWithoutPackageInput> | Prisma.DayItineraryCreateWithoutPackageInput[] | Prisma.DayItineraryUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.DayItineraryCreateOrConnectWithoutPackageInput | Prisma.DayItineraryCreateOrConnectWithoutPackageInput[]
  upsert?: Prisma.DayItineraryUpsertWithWhereUniqueWithoutPackageInput | Prisma.DayItineraryUpsertWithWhereUniqueWithoutPackageInput[]
  createMany?: Prisma.DayItineraryCreateManyPackageInputEnvelope
  set?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  disconnect?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  delete?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  connect?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  update?: Prisma.DayItineraryUpdateWithWhereUniqueWithoutPackageInput | Prisma.DayItineraryUpdateWithWhereUniqueWithoutPackageInput[]
  updateMany?: Prisma.DayItineraryUpdateManyWithWhereWithoutPackageInput | Prisma.DayItineraryUpdateManyWithWhereWithoutPackageInput[]
  deleteMany?: Prisma.DayItineraryScalarWhereInput | Prisma.DayItineraryScalarWhereInput[]
}

export type DayItineraryUncheckedUpdateManyWithoutPackageNestedInput = {
  create?: Prisma.XOR<Prisma.DayItineraryCreateWithoutPackageInput, Prisma.DayItineraryUncheckedCreateWithoutPackageInput> | Prisma.DayItineraryCreateWithoutPackageInput[] | Prisma.DayItineraryUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.DayItineraryCreateOrConnectWithoutPackageInput | Prisma.DayItineraryCreateOrConnectWithoutPackageInput[]
  upsert?: Prisma.DayItineraryUpsertWithWhereUniqueWithoutPackageInput | Prisma.DayItineraryUpsertWithWhereUniqueWithoutPackageInput[]
  createMany?: Prisma.DayItineraryCreateManyPackageInputEnvelope
  set?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  disconnect?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  delete?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  connect?: Prisma.DayItineraryWhereUniqueInput | Prisma.DayItineraryWhereUniqueInput[]
  update?: Prisma.DayItineraryUpdateWithWhereUniqueWithoutPackageInput | Prisma.DayItineraryUpdateWithWhereUniqueWithoutPackageInput[]
  updateMany?: Prisma.DayItineraryUpdateManyWithWhereWithoutPackageInput | Prisma.DayItineraryUpdateManyWithWhereWithoutPackageInput[]
  deleteMany?: Prisma.DayItineraryScalarWhereInput | Prisma.DayItineraryScalarWhereInput[]
}

export type DayItineraryCreateNestedOneWithoutFeaturesInput = {
  create?: Prisma.XOR<Prisma.DayItineraryCreateWithoutFeaturesInput, Prisma.DayItineraryUncheckedCreateWithoutFeaturesInput>
  connectOrCreate?: Prisma.DayItineraryCreateOrConnectWithoutFeaturesInput
  connect?: Prisma.DayItineraryWhereUniqueInput
}

export type DayItineraryUpdateOneRequiredWithoutFeaturesNestedInput = {
  create?: Prisma.XOR<Prisma.DayItineraryCreateWithoutFeaturesInput, Prisma.DayItineraryUncheckedCreateWithoutFeaturesInput>
  connectOrCreate?: Prisma.DayItineraryCreateOrConnectWithoutFeaturesInput
  upsert?: Prisma.DayItineraryUpsertWithoutFeaturesInput
  connect?: Prisma.DayItineraryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DayItineraryUpdateToOneWithWhereWithoutFeaturesInput, Prisma.DayItineraryUpdateWithoutFeaturesInput>, Prisma.DayItineraryUncheckedUpdateWithoutFeaturesInput>
}

export type DayItineraryCreateWithoutPackageInput = {
  id?: string
  dayNumber: number
  description: string
  features?: Prisma.FeaturedItemsCreateNestedManyWithoutDayItineraryInput
}

export type DayItineraryUncheckedCreateWithoutPackageInput = {
  id?: string
  dayNumber: number
  description: string
  features?: Prisma.FeaturedItemsUncheckedCreateNestedManyWithoutDayItineraryInput
}

export type DayItineraryCreateOrConnectWithoutPackageInput = {
  where: Prisma.DayItineraryWhereUniqueInput
  create: Prisma.XOR<Prisma.DayItineraryCreateWithoutPackageInput, Prisma.DayItineraryUncheckedCreateWithoutPackageInput>
}

export type DayItineraryCreateManyPackageInputEnvelope = {
  data: Prisma.DayItineraryCreateManyPackageInput | Prisma.DayItineraryCreateManyPackageInput[]
  skipDuplicates?: boolean
}

export type DayItineraryUpsertWithWhereUniqueWithoutPackageInput = {
  where: Prisma.DayItineraryWhereUniqueInput
  update: Prisma.XOR<Prisma.DayItineraryUpdateWithoutPackageInput, Prisma.DayItineraryUncheckedUpdateWithoutPackageInput>
  create: Prisma.XOR<Prisma.DayItineraryCreateWithoutPackageInput, Prisma.DayItineraryUncheckedCreateWithoutPackageInput>
}

export type DayItineraryUpdateWithWhereUniqueWithoutPackageInput = {
  where: Prisma.DayItineraryWhereUniqueInput
  data: Prisma.XOR<Prisma.DayItineraryUpdateWithoutPackageInput, Prisma.DayItineraryUncheckedUpdateWithoutPackageInput>
}

export type DayItineraryUpdateManyWithWhereWithoutPackageInput = {
  where: Prisma.DayItineraryScalarWhereInput
  data: Prisma.XOR<Prisma.DayItineraryUpdateManyMutationInput, Prisma.DayItineraryUncheckedUpdateManyWithoutPackageInput>
}

export type DayItineraryScalarWhereInput = {
  AND?: Prisma.DayItineraryScalarWhereInput | Prisma.DayItineraryScalarWhereInput[]
  OR?: Prisma.DayItineraryScalarWhereInput[]
  NOT?: Prisma.DayItineraryScalarWhereInput | Prisma.DayItineraryScalarWhereInput[]
  id?: Prisma.StringFilter<"DayItinerary"> | string
  dayNumber?: Prisma.IntFilter<"DayItinerary"> | number
  description?: Prisma.StringFilter<"DayItinerary"> | string
  packageId?: Prisma.StringFilter<"DayItinerary"> | string
}

export type DayItineraryCreateWithoutFeaturesInput = {
  id?: string
  dayNumber: number
  description: string
  package: Prisma.PackageCreateNestedOneWithoutItinerariesInput
}

export type DayItineraryUncheckedCreateWithoutFeaturesInput = {
  id?: string
  dayNumber: number
  description: string
  packageId: string
}

export type DayItineraryCreateOrConnectWithoutFeaturesInput = {
  where: Prisma.DayItineraryWhereUniqueInput
  create: Prisma.XOR<Prisma.DayItineraryCreateWithoutFeaturesInput, Prisma.DayItineraryUncheckedCreateWithoutFeaturesInput>
}

export type DayItineraryUpsertWithoutFeaturesInput = {
  update: Prisma.XOR<Prisma.DayItineraryUpdateWithoutFeaturesInput, Prisma.DayItineraryUncheckedUpdateWithoutFeaturesInput>
  create: Prisma.XOR<Prisma.DayItineraryCreateWithoutFeaturesInput, Prisma.DayItineraryUncheckedCreateWithoutFeaturesInput>
  where?: Prisma.DayItineraryWhereInput
}

export type DayItineraryUpdateToOneWithWhereWithoutFeaturesInput = {
  where?: Prisma.DayItineraryWhereInput
  data: Prisma.XOR<Prisma.DayItineraryUpdateWithoutFeaturesInput, Prisma.DayItineraryUncheckedUpdateWithoutFeaturesInput>
}

export type DayItineraryUpdateWithoutFeaturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  package?: Prisma.PackageUpdateOneRequiredWithoutItinerariesNestedInput
}

export type DayItineraryUncheckedUpdateWithoutFeaturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DayItineraryCreateManyPackageInput = {
  id?: string
  dayNumber: number
  description: string
}

export type DayItineraryUpdateWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.FeaturedItemsUpdateManyWithoutDayItineraryNestedInput
}

export type DayItineraryUncheckedUpdateWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.FeaturedItemsUncheckedUpdateManyWithoutDayItineraryNestedInput
}

export type DayItineraryUncheckedUpdateManyWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayNumber?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type DayItineraryCountOutputType
 */

export type DayItineraryCountOutputType = {
  features: number
}

export type DayItineraryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  features?: boolean | DayItineraryCountOutputTypeCountFeaturesArgs
}

/**
 * DayItineraryCountOutputType without action
 */
export type DayItineraryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItineraryCountOutputType
   */
  select?: Prisma.DayItineraryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DayItineraryCountOutputType without action
 */
export type DayItineraryCountOutputTypeCountFeaturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeaturedItemsWhereInput
}


export type DayItinerarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dayNumber?: boolean
  description?: boolean
  packageId?: boolean
  features?: boolean | Prisma.DayItinerary$featuresArgs<ExtArgs>
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.DayItineraryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dayItinerary"]>

export type DayItinerarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dayNumber?: boolean
  description?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dayItinerary"]>

export type DayItinerarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dayNumber?: boolean
  description?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dayItinerary"]>

export type DayItinerarySelectScalar = {
  id?: boolean
  dayNumber?: boolean
  description?: boolean
  packageId?: boolean
}

export type DayItineraryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dayNumber" | "description" | "packageId", ExtArgs["result"]["dayItinerary"]>
export type DayItineraryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  features?: boolean | Prisma.DayItinerary$featuresArgs<ExtArgs>
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.DayItineraryCountOutputTypeDefaultArgs<ExtArgs>
}
export type DayItineraryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}
export type DayItineraryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}

export type $DayItineraryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DayItinerary"
  objects: {
    features: Prisma.$FeaturedItemsPayload<ExtArgs>[]
    package: Prisma.$PackagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    dayNumber: number
    description: string
    packageId: string
  }, ExtArgs["result"]["dayItinerary"]>
  composites: {}
}

export type DayItineraryGetPayload<S extends boolean | null | undefined | DayItineraryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload, S>

export type DayItineraryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DayItineraryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DayItineraryCountAggregateInputType | true
  }

export interface DayItineraryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DayItinerary'], meta: { name: 'DayItinerary' } }
  /**
   * Find zero or one DayItinerary that matches the filter.
   * @param {DayItineraryFindUniqueArgs} args - Arguments to find a DayItinerary
   * @example
   * // Get one DayItinerary
   * const dayItinerary = await prisma.dayItinerary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DayItineraryFindUniqueArgs>(args: Prisma.SelectSubset<T, DayItineraryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DayItinerary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DayItineraryFindUniqueOrThrowArgs} args - Arguments to find a DayItinerary
   * @example
   * // Get one DayItinerary
   * const dayItinerary = await prisma.dayItinerary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DayItineraryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DayItineraryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DayItinerary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryFindFirstArgs} args - Arguments to find a DayItinerary
   * @example
   * // Get one DayItinerary
   * const dayItinerary = await prisma.dayItinerary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DayItineraryFindFirstArgs>(args?: Prisma.SelectSubset<T, DayItineraryFindFirstArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DayItinerary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryFindFirstOrThrowArgs} args - Arguments to find a DayItinerary
   * @example
   * // Get one DayItinerary
   * const dayItinerary = await prisma.dayItinerary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DayItineraryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DayItineraryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DayItineraries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DayItineraries
   * const dayItineraries = await prisma.dayItinerary.findMany()
   * 
   * // Get first 10 DayItineraries
   * const dayItineraries = await prisma.dayItinerary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dayItineraryWithIdOnly = await prisma.dayItinerary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DayItineraryFindManyArgs>(args?: Prisma.SelectSubset<T, DayItineraryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DayItinerary.
   * @param {DayItineraryCreateArgs} args - Arguments to create a DayItinerary.
   * @example
   * // Create one DayItinerary
   * const DayItinerary = await prisma.dayItinerary.create({
   *   data: {
   *     // ... data to create a DayItinerary
   *   }
   * })
   * 
   */
  create<T extends DayItineraryCreateArgs>(args: Prisma.SelectSubset<T, DayItineraryCreateArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DayItineraries.
   * @param {DayItineraryCreateManyArgs} args - Arguments to create many DayItineraries.
   * @example
   * // Create many DayItineraries
   * const dayItinerary = await prisma.dayItinerary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DayItineraryCreateManyArgs>(args?: Prisma.SelectSubset<T, DayItineraryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DayItineraries and returns the data saved in the database.
   * @param {DayItineraryCreateManyAndReturnArgs} args - Arguments to create many DayItineraries.
   * @example
   * // Create many DayItineraries
   * const dayItinerary = await prisma.dayItinerary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DayItineraries and only return the `id`
   * const dayItineraryWithIdOnly = await prisma.dayItinerary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DayItineraryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DayItineraryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DayItinerary.
   * @param {DayItineraryDeleteArgs} args - Arguments to delete one DayItinerary.
   * @example
   * // Delete one DayItinerary
   * const DayItinerary = await prisma.dayItinerary.delete({
   *   where: {
   *     // ... filter to delete one DayItinerary
   *   }
   * })
   * 
   */
  delete<T extends DayItineraryDeleteArgs>(args: Prisma.SelectSubset<T, DayItineraryDeleteArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DayItinerary.
   * @param {DayItineraryUpdateArgs} args - Arguments to update one DayItinerary.
   * @example
   * // Update one DayItinerary
   * const dayItinerary = await prisma.dayItinerary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DayItineraryUpdateArgs>(args: Prisma.SelectSubset<T, DayItineraryUpdateArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DayItineraries.
   * @param {DayItineraryDeleteManyArgs} args - Arguments to filter DayItineraries to delete.
   * @example
   * // Delete a few DayItineraries
   * const { count } = await prisma.dayItinerary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DayItineraryDeleteManyArgs>(args?: Prisma.SelectSubset<T, DayItineraryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DayItineraries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DayItineraries
   * const dayItinerary = await prisma.dayItinerary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DayItineraryUpdateManyArgs>(args: Prisma.SelectSubset<T, DayItineraryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DayItineraries and returns the data updated in the database.
   * @param {DayItineraryUpdateManyAndReturnArgs} args - Arguments to update many DayItineraries.
   * @example
   * // Update many DayItineraries
   * const dayItinerary = await prisma.dayItinerary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DayItineraries and only return the `id`
   * const dayItineraryWithIdOnly = await prisma.dayItinerary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DayItineraryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DayItineraryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DayItinerary.
   * @param {DayItineraryUpsertArgs} args - Arguments to update or create a DayItinerary.
   * @example
   * // Update or create a DayItinerary
   * const dayItinerary = await prisma.dayItinerary.upsert({
   *   create: {
   *     // ... data to create a DayItinerary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DayItinerary we want to update
   *   }
   * })
   */
  upsert<T extends DayItineraryUpsertArgs>(args: Prisma.SelectSubset<T, DayItineraryUpsertArgs<ExtArgs>>): Prisma.Prisma__DayItineraryClient<runtime.Types.Result.GetResult<Prisma.$DayItineraryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DayItineraries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryCountArgs} args - Arguments to filter DayItineraries to count.
   * @example
   * // Count the number of DayItineraries
   * const count = await prisma.dayItinerary.count({
   *   where: {
   *     // ... the filter for the DayItineraries we want to count
   *   }
   * })
  **/
  count<T extends DayItineraryCountArgs>(
    args?: Prisma.Subset<T, DayItineraryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DayItineraryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DayItinerary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DayItineraryAggregateArgs>(args: Prisma.Subset<T, DayItineraryAggregateArgs>): Prisma.PrismaPromise<GetDayItineraryAggregateType<T>>

  /**
   * Group by DayItinerary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DayItineraryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DayItineraryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DayItineraryGroupByArgs['orderBy'] }
      : { orderBy?: DayItineraryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DayItineraryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDayItineraryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DayItinerary model
 */
readonly fields: DayItineraryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DayItinerary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DayItineraryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  features<T extends Prisma.DayItinerary$featuresArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DayItinerary$featuresArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeaturedItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  package<T extends Prisma.PackageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PackageDefaultArgs<ExtArgs>>): Prisma.Prisma__PackageClient<runtime.Types.Result.GetResult<Prisma.$PackagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DayItinerary model
 */
export interface DayItineraryFieldRefs {
  readonly id: Prisma.FieldRef<"DayItinerary", 'String'>
  readonly dayNumber: Prisma.FieldRef<"DayItinerary", 'Int'>
  readonly description: Prisma.FieldRef<"DayItinerary", 'String'>
  readonly packageId: Prisma.FieldRef<"DayItinerary", 'String'>
}
    

// Custom InputTypes
/**
 * DayItinerary findUnique
 */
export type DayItineraryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * Filter, which DayItinerary to fetch.
   */
  where: Prisma.DayItineraryWhereUniqueInput
}

/**
 * DayItinerary findUniqueOrThrow
 */
export type DayItineraryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * Filter, which DayItinerary to fetch.
   */
  where: Prisma.DayItineraryWhereUniqueInput
}

/**
 * DayItinerary findFirst
 */
export type DayItineraryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * Filter, which DayItinerary to fetch.
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DayItineraries to fetch.
   */
  orderBy?: Prisma.DayItineraryOrderByWithRelationInput | Prisma.DayItineraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DayItineraries.
   */
  cursor?: Prisma.DayItineraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DayItineraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DayItineraries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DayItineraries.
   */
  distinct?: Prisma.DayItineraryScalarFieldEnum | Prisma.DayItineraryScalarFieldEnum[]
}

/**
 * DayItinerary findFirstOrThrow
 */
export type DayItineraryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * Filter, which DayItinerary to fetch.
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DayItineraries to fetch.
   */
  orderBy?: Prisma.DayItineraryOrderByWithRelationInput | Prisma.DayItineraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DayItineraries.
   */
  cursor?: Prisma.DayItineraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DayItineraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DayItineraries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DayItineraries.
   */
  distinct?: Prisma.DayItineraryScalarFieldEnum | Prisma.DayItineraryScalarFieldEnum[]
}

/**
 * DayItinerary findMany
 */
export type DayItineraryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * Filter, which DayItineraries to fetch.
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DayItineraries to fetch.
   */
  orderBy?: Prisma.DayItineraryOrderByWithRelationInput | Prisma.DayItineraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DayItineraries.
   */
  cursor?: Prisma.DayItineraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DayItineraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DayItineraries.
   */
  skip?: number
  distinct?: Prisma.DayItineraryScalarFieldEnum | Prisma.DayItineraryScalarFieldEnum[]
}

/**
 * DayItinerary create
 */
export type DayItineraryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * The data needed to create a DayItinerary.
   */
  data: Prisma.XOR<Prisma.DayItineraryCreateInput, Prisma.DayItineraryUncheckedCreateInput>
}

/**
 * DayItinerary createMany
 */
export type DayItineraryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DayItineraries.
   */
  data: Prisma.DayItineraryCreateManyInput | Prisma.DayItineraryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DayItinerary createManyAndReturn
 */
export type DayItineraryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * The data used to create many DayItineraries.
   */
  data: Prisma.DayItineraryCreateManyInput | Prisma.DayItineraryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DayItinerary update
 */
export type DayItineraryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * The data needed to update a DayItinerary.
   */
  data: Prisma.XOR<Prisma.DayItineraryUpdateInput, Prisma.DayItineraryUncheckedUpdateInput>
  /**
   * Choose, which DayItinerary to update.
   */
  where: Prisma.DayItineraryWhereUniqueInput
}

/**
 * DayItinerary updateMany
 */
export type DayItineraryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DayItineraries.
   */
  data: Prisma.XOR<Prisma.DayItineraryUpdateManyMutationInput, Prisma.DayItineraryUncheckedUpdateManyInput>
  /**
   * Filter which DayItineraries to update
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * Limit how many DayItineraries to update.
   */
  limit?: number
}

/**
 * DayItinerary updateManyAndReturn
 */
export type DayItineraryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * The data used to update DayItineraries.
   */
  data: Prisma.XOR<Prisma.DayItineraryUpdateManyMutationInput, Prisma.DayItineraryUncheckedUpdateManyInput>
  /**
   * Filter which DayItineraries to update
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * Limit how many DayItineraries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DayItinerary upsert
 */
export type DayItineraryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * The filter to search for the DayItinerary to update in case it exists.
   */
  where: Prisma.DayItineraryWhereUniqueInput
  /**
   * In case the DayItinerary found by the `where` argument doesn't exist, create a new DayItinerary with this data.
   */
  create: Prisma.XOR<Prisma.DayItineraryCreateInput, Prisma.DayItineraryUncheckedCreateInput>
  /**
   * In case the DayItinerary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DayItineraryUpdateInput, Prisma.DayItineraryUncheckedUpdateInput>
}

/**
 * DayItinerary delete
 */
export type DayItineraryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
  /**
   * Filter which DayItinerary to delete.
   */
  where: Prisma.DayItineraryWhereUniqueInput
}

/**
 * DayItinerary deleteMany
 */
export type DayItineraryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DayItineraries to delete
   */
  where?: Prisma.DayItineraryWhereInput
  /**
   * Limit how many DayItineraries to delete.
   */
  limit?: number
}

/**
 * DayItinerary.features
 */
export type DayItinerary$featuresArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeaturedItems
   */
  select?: Prisma.FeaturedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeaturedItems
   */
  omit?: Prisma.FeaturedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeaturedItemsInclude<ExtArgs> | null
  where?: Prisma.FeaturedItemsWhereInput
  orderBy?: Prisma.FeaturedItemsOrderByWithRelationInput | Prisma.FeaturedItemsOrderByWithRelationInput[]
  cursor?: Prisma.FeaturedItemsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FeaturedItemsScalarFieldEnum | Prisma.FeaturedItemsScalarFieldEnum[]
}

/**
 * DayItinerary without action
 */
export type DayItineraryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DayItinerary
   */
  select?: Prisma.DayItinerarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DayItinerary
   */
  omit?: Prisma.DayItineraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DayItineraryInclude<ExtArgs> | null
}
