
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `ExcludedItems` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ExcludedItems
 * 
 */
export type ExcludedItemsModel = runtime.Types.Result.DefaultSelection<Prisma.$ExcludedItemsPayload>

export type AggregateExcludedItems = {
  _count: ExcludedItemsCountAggregateOutputType | null
  _min: ExcludedItemsMinAggregateOutputType | null
  _max: ExcludedItemsMaxAggregateOutputType | null
}

export type ExcludedItemsMinAggregateOutputType = {
  id: string | null
  item: string | null
  packageId: string | null
}

export type ExcludedItemsMaxAggregateOutputType = {
  id: string | null
  item: string | null
  packageId: string | null
}

export type ExcludedItemsCountAggregateOutputType = {
  id: number
  item: number
  packageId: number
  _all: number
}


export type ExcludedItemsMinAggregateInputType = {
  id?: true
  item?: true
  packageId?: true
}

export type ExcludedItemsMaxAggregateInputType = {
  id?: true
  item?: true
  packageId?: true
}

export type ExcludedItemsCountAggregateInputType = {
  id?: true
  item?: true
  packageId?: true
  _all?: true
}

export type ExcludedItemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExcludedItems to aggregate.
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExcludedItems to fetch.
   */
  orderBy?: Prisma.ExcludedItemsOrderByWithRelationInput | Prisma.ExcludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExcludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExcludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExcludedItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ExcludedItems
  **/
  _count?: true | ExcludedItemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExcludedItemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExcludedItemsMaxAggregateInputType
}

export type GetExcludedItemsAggregateType<T extends ExcludedItemsAggregateArgs> = {
      [P in keyof T & keyof AggregateExcludedItems]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExcludedItems[P]>
    : Prisma.GetScalarType<T[P], AggregateExcludedItems[P]>
}




export type ExcludedItemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExcludedItemsWhereInput
  orderBy?: Prisma.ExcludedItemsOrderByWithAggregationInput | Prisma.ExcludedItemsOrderByWithAggregationInput[]
  by: Prisma.ExcludedItemsScalarFieldEnum[] | Prisma.ExcludedItemsScalarFieldEnum
  having?: Prisma.ExcludedItemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExcludedItemsCountAggregateInputType | true
  _min?: ExcludedItemsMinAggregateInputType
  _max?: ExcludedItemsMaxAggregateInputType
}

export type ExcludedItemsGroupByOutputType = {
  id: string
  item: string
  packageId: string
  _count: ExcludedItemsCountAggregateOutputType | null
  _min: ExcludedItemsMinAggregateOutputType | null
  _max: ExcludedItemsMaxAggregateOutputType | null
}

type GetExcludedItemsGroupByPayload<T extends ExcludedItemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExcludedItemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExcludedItemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExcludedItemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExcludedItemsGroupByOutputType[P]>
      }
    >
  >



export type ExcludedItemsWhereInput = {
  AND?: Prisma.ExcludedItemsWhereInput | Prisma.ExcludedItemsWhereInput[]
  OR?: Prisma.ExcludedItemsWhereInput[]
  NOT?: Prisma.ExcludedItemsWhereInput | Prisma.ExcludedItemsWhereInput[]
  id?: Prisma.StringFilter<"ExcludedItems"> | string
  item?: Prisma.StringFilter<"ExcludedItems"> | string
  packageId?: Prisma.StringFilter<"ExcludedItems"> | string
  package?: Prisma.XOR<Prisma.PackageScalarRelationFilter, Prisma.PackageWhereInput>
}

export type ExcludedItemsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
  package?: Prisma.PackageOrderByWithRelationInput
}

export type ExcludedItemsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ExcludedItemsWhereInput | Prisma.ExcludedItemsWhereInput[]
  OR?: Prisma.ExcludedItemsWhereInput[]
  NOT?: Prisma.ExcludedItemsWhereInput | Prisma.ExcludedItemsWhereInput[]
  item?: Prisma.StringFilter<"ExcludedItems"> | string
  packageId?: Prisma.StringFilter<"ExcludedItems"> | string
  package?: Prisma.XOR<Prisma.PackageScalarRelationFilter, Prisma.PackageWhereInput>
}, "id">

export type ExcludedItemsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
  _count?: Prisma.ExcludedItemsCountOrderByAggregateInput
  _max?: Prisma.ExcludedItemsMaxOrderByAggregateInput
  _min?: Prisma.ExcludedItemsMinOrderByAggregateInput
}

export type ExcludedItemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExcludedItemsScalarWhereWithAggregatesInput | Prisma.ExcludedItemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExcludedItemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExcludedItemsScalarWhereWithAggregatesInput | Prisma.ExcludedItemsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ExcludedItems"> | string
  item?: Prisma.StringWithAggregatesFilter<"ExcludedItems"> | string
  packageId?: Prisma.StringWithAggregatesFilter<"ExcludedItems"> | string
}

export type ExcludedItemsCreateInput = {
  id?: string
  item: string
  package: Prisma.PackageCreateNestedOneWithoutExclusionsInput
}

export type ExcludedItemsUncheckedCreateInput = {
  id?: string
  item: string
  packageId: string
}

export type ExcludedItemsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
  package?: Prisma.PackageUpdateOneRequiredWithoutExclusionsNestedInput
}

export type ExcludedItemsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExcludedItemsCreateManyInput = {
  id?: string
  item: string
  packageId: string
}

export type ExcludedItemsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExcludedItemsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExcludedItemsListRelationFilter = {
  every?: Prisma.ExcludedItemsWhereInput
  some?: Prisma.ExcludedItemsWhereInput
  none?: Prisma.ExcludedItemsWhereInput
}

export type ExcludedItemsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExcludedItemsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type ExcludedItemsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type ExcludedItemsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type ExcludedItemsCreateNestedManyWithoutPackageInput = {
  create?: Prisma.XOR<Prisma.ExcludedItemsCreateWithoutPackageInput, Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput> | Prisma.ExcludedItemsCreateWithoutPackageInput[] | Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput | Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput[]
  createMany?: Prisma.ExcludedItemsCreateManyPackageInputEnvelope
  connect?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
}

export type ExcludedItemsUncheckedCreateNestedManyWithoutPackageInput = {
  create?: Prisma.XOR<Prisma.ExcludedItemsCreateWithoutPackageInput, Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput> | Prisma.ExcludedItemsCreateWithoutPackageInput[] | Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput | Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput[]
  createMany?: Prisma.ExcludedItemsCreateManyPackageInputEnvelope
  connect?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
}

export type ExcludedItemsUpdateManyWithoutPackageNestedInput = {
  create?: Prisma.XOR<Prisma.ExcludedItemsCreateWithoutPackageInput, Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput> | Prisma.ExcludedItemsCreateWithoutPackageInput[] | Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput | Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput[]
  upsert?: Prisma.ExcludedItemsUpsertWithWhereUniqueWithoutPackageInput | Prisma.ExcludedItemsUpsertWithWhereUniqueWithoutPackageInput[]
  createMany?: Prisma.ExcludedItemsCreateManyPackageInputEnvelope
  set?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  disconnect?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  delete?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  connect?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  update?: Prisma.ExcludedItemsUpdateWithWhereUniqueWithoutPackageInput | Prisma.ExcludedItemsUpdateWithWhereUniqueWithoutPackageInput[]
  updateMany?: Prisma.ExcludedItemsUpdateManyWithWhereWithoutPackageInput | Prisma.ExcludedItemsUpdateManyWithWhereWithoutPackageInput[]
  deleteMany?: Prisma.ExcludedItemsScalarWhereInput | Prisma.ExcludedItemsScalarWhereInput[]
}

export type ExcludedItemsUncheckedUpdateManyWithoutPackageNestedInput = {
  create?: Prisma.XOR<Prisma.ExcludedItemsCreateWithoutPackageInput, Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput> | Prisma.ExcludedItemsCreateWithoutPackageInput[] | Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput | Prisma.ExcludedItemsCreateOrConnectWithoutPackageInput[]
  upsert?: Prisma.ExcludedItemsUpsertWithWhereUniqueWithoutPackageInput | Prisma.ExcludedItemsUpsertWithWhereUniqueWithoutPackageInput[]
  createMany?: Prisma.ExcludedItemsCreateManyPackageInputEnvelope
  set?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  disconnect?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  delete?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  connect?: Prisma.ExcludedItemsWhereUniqueInput | Prisma.ExcludedItemsWhereUniqueInput[]
  update?: Prisma.ExcludedItemsUpdateWithWhereUniqueWithoutPackageInput | Prisma.ExcludedItemsUpdateWithWhereUniqueWithoutPackageInput[]
  updateMany?: Prisma.ExcludedItemsUpdateManyWithWhereWithoutPackageInput | Prisma.ExcludedItemsUpdateManyWithWhereWithoutPackageInput[]
  deleteMany?: Prisma.ExcludedItemsScalarWhereInput | Prisma.ExcludedItemsScalarWhereInput[]
}

export type ExcludedItemsCreateWithoutPackageInput = {
  id?: string
  item: string
}

export type ExcludedItemsUncheckedCreateWithoutPackageInput = {
  id?: string
  item: string
}

export type ExcludedItemsCreateOrConnectWithoutPackageInput = {
  where: Prisma.ExcludedItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.ExcludedItemsCreateWithoutPackageInput, Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput>
}

export type ExcludedItemsCreateManyPackageInputEnvelope = {
  data: Prisma.ExcludedItemsCreateManyPackageInput | Prisma.ExcludedItemsCreateManyPackageInput[]
  skipDuplicates?: boolean
}

export type ExcludedItemsUpsertWithWhereUniqueWithoutPackageInput = {
  where: Prisma.ExcludedItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.ExcludedItemsUpdateWithoutPackageInput, Prisma.ExcludedItemsUncheckedUpdateWithoutPackageInput>
  create: Prisma.XOR<Prisma.ExcludedItemsCreateWithoutPackageInput, Prisma.ExcludedItemsUncheckedCreateWithoutPackageInput>
}

export type ExcludedItemsUpdateWithWhereUniqueWithoutPackageInput = {
  where: Prisma.ExcludedItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.ExcludedItemsUpdateWithoutPackageInput, Prisma.ExcludedItemsUncheckedUpdateWithoutPackageInput>
}

export type ExcludedItemsUpdateManyWithWhereWithoutPackageInput = {
  where: Prisma.ExcludedItemsScalarWhereInput
  data: Prisma.XOR<Prisma.ExcludedItemsUpdateManyMutationInput, Prisma.ExcludedItemsUncheckedUpdateManyWithoutPackageInput>
}

export type ExcludedItemsScalarWhereInput = {
  AND?: Prisma.ExcludedItemsScalarWhereInput | Prisma.ExcludedItemsScalarWhereInput[]
  OR?: Prisma.ExcludedItemsScalarWhereInput[]
  NOT?: Prisma.ExcludedItemsScalarWhereInput | Prisma.ExcludedItemsScalarWhereInput[]
  id?: Prisma.StringFilter<"ExcludedItems"> | string
  item?: Prisma.StringFilter<"ExcludedItems"> | string
  packageId?: Prisma.StringFilter<"ExcludedItems"> | string
}

export type ExcludedItemsCreateManyPackageInput = {
  id?: string
  item: string
}

export type ExcludedItemsUpdateWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExcludedItemsUncheckedUpdateWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExcludedItemsUncheckedUpdateManyWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ExcludedItemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  item?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["excludedItems"]>

export type ExcludedItemsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  item?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["excludedItems"]>

export type ExcludedItemsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  item?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["excludedItems"]>

export type ExcludedItemsSelectScalar = {
  id?: boolean
  item?: boolean
  packageId?: boolean
}

export type ExcludedItemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "item" | "packageId", ExtArgs["result"]["excludedItems"]>
export type ExcludedItemsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}
export type ExcludedItemsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}
export type ExcludedItemsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}

export type $ExcludedItemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ExcludedItems"
  objects: {
    package: Prisma.$PackagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    item: string
    packageId: string
  }, ExtArgs["result"]["excludedItems"]>
  composites: {}
}

export type ExcludedItemsGetPayload<S extends boolean | null | undefined | ExcludedItemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload, S>

export type ExcludedItemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExcludedItemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExcludedItemsCountAggregateInputType | true
  }

export interface ExcludedItemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ExcludedItems'], meta: { name: 'ExcludedItems' } }
  /**
   * Find zero or one ExcludedItems that matches the filter.
   * @param {ExcludedItemsFindUniqueArgs} args - Arguments to find a ExcludedItems
   * @example
   * // Get one ExcludedItems
   * const excludedItems = await prisma.excludedItems.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExcludedItemsFindUniqueArgs>(args: Prisma.SelectSubset<T, ExcludedItemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ExcludedItems that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExcludedItemsFindUniqueOrThrowArgs} args - Arguments to find a ExcludedItems
   * @example
   * // Get one ExcludedItems
   * const excludedItems = await prisma.excludedItems.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExcludedItemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExcludedItemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExcludedItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsFindFirstArgs} args - Arguments to find a ExcludedItems
   * @example
   * // Get one ExcludedItems
   * const excludedItems = await prisma.excludedItems.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExcludedItemsFindFirstArgs>(args?: Prisma.SelectSubset<T, ExcludedItemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExcludedItems that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsFindFirstOrThrowArgs} args - Arguments to find a ExcludedItems
   * @example
   * // Get one ExcludedItems
   * const excludedItems = await prisma.excludedItems.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExcludedItemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExcludedItemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ExcludedItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExcludedItems
   * const excludedItems = await prisma.excludedItems.findMany()
   * 
   * // Get first 10 ExcludedItems
   * const excludedItems = await prisma.excludedItems.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const excludedItemsWithIdOnly = await prisma.excludedItems.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExcludedItemsFindManyArgs>(args?: Prisma.SelectSubset<T, ExcludedItemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ExcludedItems.
   * @param {ExcludedItemsCreateArgs} args - Arguments to create a ExcludedItems.
   * @example
   * // Create one ExcludedItems
   * const ExcludedItems = await prisma.excludedItems.create({
   *   data: {
   *     // ... data to create a ExcludedItems
   *   }
   * })
   * 
   */
  create<T extends ExcludedItemsCreateArgs>(args: Prisma.SelectSubset<T, ExcludedItemsCreateArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ExcludedItems.
   * @param {ExcludedItemsCreateManyArgs} args - Arguments to create many ExcludedItems.
   * @example
   * // Create many ExcludedItems
   * const excludedItems = await prisma.excludedItems.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExcludedItemsCreateManyArgs>(args?: Prisma.SelectSubset<T, ExcludedItemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExcludedItems and returns the data saved in the database.
   * @param {ExcludedItemsCreateManyAndReturnArgs} args - Arguments to create many ExcludedItems.
   * @example
   * // Create many ExcludedItems
   * const excludedItems = await prisma.excludedItems.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ExcludedItems and only return the `id`
   * const excludedItemsWithIdOnly = await prisma.excludedItems.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExcludedItemsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExcludedItemsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ExcludedItems.
   * @param {ExcludedItemsDeleteArgs} args - Arguments to delete one ExcludedItems.
   * @example
   * // Delete one ExcludedItems
   * const ExcludedItems = await prisma.excludedItems.delete({
   *   where: {
   *     // ... filter to delete one ExcludedItems
   *   }
   * })
   * 
   */
  delete<T extends ExcludedItemsDeleteArgs>(args: Prisma.SelectSubset<T, ExcludedItemsDeleteArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ExcludedItems.
   * @param {ExcludedItemsUpdateArgs} args - Arguments to update one ExcludedItems.
   * @example
   * // Update one ExcludedItems
   * const excludedItems = await prisma.excludedItems.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExcludedItemsUpdateArgs>(args: Prisma.SelectSubset<T, ExcludedItemsUpdateArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ExcludedItems.
   * @param {ExcludedItemsDeleteManyArgs} args - Arguments to filter ExcludedItems to delete.
   * @example
   * // Delete a few ExcludedItems
   * const { count } = await prisma.excludedItems.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExcludedItemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExcludedItemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExcludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExcludedItems
   * const excludedItems = await prisma.excludedItems.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExcludedItemsUpdateManyArgs>(args: Prisma.SelectSubset<T, ExcludedItemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExcludedItems and returns the data updated in the database.
   * @param {ExcludedItemsUpdateManyAndReturnArgs} args - Arguments to update many ExcludedItems.
   * @example
   * // Update many ExcludedItems
   * const excludedItems = await prisma.excludedItems.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ExcludedItems and only return the `id`
   * const excludedItemsWithIdOnly = await prisma.excludedItems.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExcludedItemsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExcludedItemsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ExcludedItems.
   * @param {ExcludedItemsUpsertArgs} args - Arguments to update or create a ExcludedItems.
   * @example
   * // Update or create a ExcludedItems
   * const excludedItems = await prisma.excludedItems.upsert({
   *   create: {
   *     // ... data to create a ExcludedItems
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExcludedItems we want to update
   *   }
   * })
   */
  upsert<T extends ExcludedItemsUpsertArgs>(args: Prisma.SelectSubset<T, ExcludedItemsUpsertArgs<ExtArgs>>): Prisma.Prisma__ExcludedItemsClient<runtime.Types.Result.GetResult<Prisma.$ExcludedItemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ExcludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsCountArgs} args - Arguments to filter ExcludedItems to count.
   * @example
   * // Count the number of ExcludedItems
   * const count = await prisma.excludedItems.count({
   *   where: {
   *     // ... the filter for the ExcludedItems we want to count
   *   }
   * })
  **/
  count<T extends ExcludedItemsCountArgs>(
    args?: Prisma.Subset<T, ExcludedItemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExcludedItemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExcludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExcludedItemsAggregateArgs>(args: Prisma.Subset<T, ExcludedItemsAggregateArgs>): Prisma.PrismaPromise<GetExcludedItemsAggregateType<T>>

  /**
   * Group by ExcludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExcludedItemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExcludedItemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExcludedItemsGroupByArgs['orderBy'] }
      : { orderBy?: ExcludedItemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExcludedItemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExcludedItemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ExcludedItems model
 */
readonly fields: ExcludedItemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExcludedItems.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExcludedItemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  package<T extends Prisma.PackageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PackageDefaultArgs<ExtArgs>>): Prisma.Prisma__PackageClient<runtime.Types.Result.GetResult<Prisma.$PackagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ExcludedItems model
 */
export interface ExcludedItemsFieldRefs {
  readonly id: Prisma.FieldRef<"ExcludedItems", 'String'>
  readonly item: Prisma.FieldRef<"ExcludedItems", 'String'>
  readonly packageId: Prisma.FieldRef<"ExcludedItems", 'String'>
}
    

// Custom InputTypes
/**
 * ExcludedItems findUnique
 */
export type ExcludedItemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which ExcludedItems to fetch.
   */
  where: Prisma.ExcludedItemsWhereUniqueInput
}

/**
 * ExcludedItems findUniqueOrThrow
 */
export type ExcludedItemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which ExcludedItems to fetch.
   */
  where: Prisma.ExcludedItemsWhereUniqueInput
}

/**
 * ExcludedItems findFirst
 */
export type ExcludedItemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which ExcludedItems to fetch.
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExcludedItems to fetch.
   */
  orderBy?: Prisma.ExcludedItemsOrderByWithRelationInput | Prisma.ExcludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExcludedItems.
   */
  cursor?: Prisma.ExcludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExcludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExcludedItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExcludedItems.
   */
  distinct?: Prisma.ExcludedItemsScalarFieldEnum | Prisma.ExcludedItemsScalarFieldEnum[]
}

/**
 * ExcludedItems findFirstOrThrow
 */
export type ExcludedItemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which ExcludedItems to fetch.
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExcludedItems to fetch.
   */
  orderBy?: Prisma.ExcludedItemsOrderByWithRelationInput | Prisma.ExcludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExcludedItems.
   */
  cursor?: Prisma.ExcludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExcludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExcludedItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExcludedItems.
   */
  distinct?: Prisma.ExcludedItemsScalarFieldEnum | Prisma.ExcludedItemsScalarFieldEnum[]
}

/**
 * ExcludedItems findMany
 */
export type ExcludedItemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which ExcludedItems to fetch.
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExcludedItems to fetch.
   */
  orderBy?: Prisma.ExcludedItemsOrderByWithRelationInput | Prisma.ExcludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ExcludedItems.
   */
  cursor?: Prisma.ExcludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExcludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExcludedItems.
   */
  skip?: number
  distinct?: Prisma.ExcludedItemsScalarFieldEnum | Prisma.ExcludedItemsScalarFieldEnum[]
}

/**
 * ExcludedItems create
 */
export type ExcludedItemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * The data needed to create a ExcludedItems.
   */
  data: Prisma.XOR<Prisma.ExcludedItemsCreateInput, Prisma.ExcludedItemsUncheckedCreateInput>
}

/**
 * ExcludedItems createMany
 */
export type ExcludedItemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ExcludedItems.
   */
  data: Prisma.ExcludedItemsCreateManyInput | Prisma.ExcludedItemsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExcludedItems createManyAndReturn
 */
export type ExcludedItemsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * The data used to create many ExcludedItems.
   */
  data: Prisma.ExcludedItemsCreateManyInput | Prisma.ExcludedItemsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ExcludedItems update
 */
export type ExcludedItemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * The data needed to update a ExcludedItems.
   */
  data: Prisma.XOR<Prisma.ExcludedItemsUpdateInput, Prisma.ExcludedItemsUncheckedUpdateInput>
  /**
   * Choose, which ExcludedItems to update.
   */
  where: Prisma.ExcludedItemsWhereUniqueInput
}

/**
 * ExcludedItems updateMany
 */
export type ExcludedItemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ExcludedItems.
   */
  data: Prisma.XOR<Prisma.ExcludedItemsUpdateManyMutationInput, Prisma.ExcludedItemsUncheckedUpdateManyInput>
  /**
   * Filter which ExcludedItems to update
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * Limit how many ExcludedItems to update.
   */
  limit?: number
}

/**
 * ExcludedItems updateManyAndReturn
 */
export type ExcludedItemsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * The data used to update ExcludedItems.
   */
  data: Prisma.XOR<Prisma.ExcludedItemsUpdateManyMutationInput, Prisma.ExcludedItemsUncheckedUpdateManyInput>
  /**
   * Filter which ExcludedItems to update
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * Limit how many ExcludedItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ExcludedItems upsert
 */
export type ExcludedItemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * The filter to search for the ExcludedItems to update in case it exists.
   */
  where: Prisma.ExcludedItemsWhereUniqueInput
  /**
   * In case the ExcludedItems found by the `where` argument doesn't exist, create a new ExcludedItems with this data.
   */
  create: Prisma.XOR<Prisma.ExcludedItemsCreateInput, Prisma.ExcludedItemsUncheckedCreateInput>
  /**
   * In case the ExcludedItems was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExcludedItemsUpdateInput, Prisma.ExcludedItemsUncheckedUpdateInput>
}

/**
 * ExcludedItems delete
 */
export type ExcludedItemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
  /**
   * Filter which ExcludedItems to delete.
   */
  where: Prisma.ExcludedItemsWhereUniqueInput
}

/**
 * ExcludedItems deleteMany
 */
export type ExcludedItemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExcludedItems to delete
   */
  where?: Prisma.ExcludedItemsWhereInput
  /**
   * Limit how many ExcludedItems to delete.
   */
  limit?: number
}

/**
 * ExcludedItems without action
 */
export type ExcludedItemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExcludedItems
   */
  select?: Prisma.ExcludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExcludedItems
   */
  omit?: Prisma.ExcludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExcludedItemsInclude<ExtArgs> | null
}
