
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `IncludedItems` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model IncludedItems
 * 
 */
export type IncludedItemsModel = runtime.Types.Result.DefaultSelection<Prisma.$IncludedItemsPayload>

export type AggregateIncludedItems = {
  _count: IncludedItemsCountAggregateOutputType | null
  _min: IncludedItemsMinAggregateOutputType | null
  _max: IncludedItemsMaxAggregateOutputType | null
}

export type IncludedItemsMinAggregateOutputType = {
  id: string | null
  item: string | null
  packageId: string | null
}

export type IncludedItemsMaxAggregateOutputType = {
  id: string | null
  item: string | null
  packageId: string | null
}

export type IncludedItemsCountAggregateOutputType = {
  id: number
  item: number
  packageId: number
  _all: number
}


export type IncludedItemsMinAggregateInputType = {
  id?: true
  item?: true
  packageId?: true
}

export type IncludedItemsMaxAggregateInputType = {
  id?: true
  item?: true
  packageId?: true
}

export type IncludedItemsCountAggregateInputType = {
  id?: true
  item?: true
  packageId?: true
  _all?: true
}

export type IncludedItemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IncludedItems to aggregate.
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IncludedItems to fetch.
   */
  orderBy?: Prisma.IncludedItemsOrderByWithRelationInput | Prisma.IncludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IncludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IncludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IncludedItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned IncludedItems
  **/
  _count?: true | IncludedItemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IncludedItemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IncludedItemsMaxAggregateInputType
}

export type GetIncludedItemsAggregateType<T extends IncludedItemsAggregateArgs> = {
      [P in keyof T & keyof AggregateIncludedItems]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIncludedItems[P]>
    : Prisma.GetScalarType<T[P], AggregateIncludedItems[P]>
}




export type IncludedItemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncludedItemsWhereInput
  orderBy?: Prisma.IncludedItemsOrderByWithAggregationInput | Prisma.IncludedItemsOrderByWithAggregationInput[]
  by: Prisma.IncludedItemsScalarFieldEnum[] | Prisma.IncludedItemsScalarFieldEnum
  having?: Prisma.IncludedItemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IncludedItemsCountAggregateInputType | true
  _min?: IncludedItemsMinAggregateInputType
  _max?: IncludedItemsMaxAggregateInputType
}

export type IncludedItemsGroupByOutputType = {
  id: string
  item: string
  packageId: string
  _count: IncludedItemsCountAggregateOutputType | null
  _min: IncludedItemsMinAggregateOutputType | null
  _max: IncludedItemsMaxAggregateOutputType | null
}

type GetIncludedItemsGroupByPayload<T extends IncludedItemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IncludedItemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IncludedItemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IncludedItemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IncludedItemsGroupByOutputType[P]>
      }
    >
  >



export type IncludedItemsWhereInput = {
  AND?: Prisma.IncludedItemsWhereInput | Prisma.IncludedItemsWhereInput[]
  OR?: Prisma.IncludedItemsWhereInput[]
  NOT?: Prisma.IncludedItemsWhereInput | Prisma.IncludedItemsWhereInput[]
  id?: Prisma.StringFilter<"IncludedItems"> | string
  item?: Prisma.StringFilter<"IncludedItems"> | string
  packageId?: Prisma.StringFilter<"IncludedItems"> | string
  package?: Prisma.XOR<Prisma.PackageScalarRelationFilter, Prisma.PackageWhereInput>
}

export type IncludedItemsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
  package?: Prisma.PackageOrderByWithRelationInput
}

export type IncludedItemsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.IncludedItemsWhereInput | Prisma.IncludedItemsWhereInput[]
  OR?: Prisma.IncludedItemsWhereInput[]
  NOT?: Prisma.IncludedItemsWhereInput | Prisma.IncludedItemsWhereInput[]
  item?: Prisma.StringFilter<"IncludedItems"> | string
  packageId?: Prisma.StringFilter<"IncludedItems"> | string
  package?: Prisma.XOR<Prisma.PackageScalarRelationFilter, Prisma.PackageWhereInput>
}, "id">

export type IncludedItemsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
  _count?: Prisma.IncludedItemsCountOrderByAggregateInput
  _max?: Prisma.IncludedItemsMaxOrderByAggregateInput
  _min?: Prisma.IncludedItemsMinOrderByAggregateInput
}

export type IncludedItemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.IncludedItemsScalarWhereWithAggregatesInput | Prisma.IncludedItemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.IncludedItemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IncludedItemsScalarWhereWithAggregatesInput | Prisma.IncludedItemsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"IncludedItems"> | string
  item?: Prisma.StringWithAggregatesFilter<"IncludedItems"> | string
  packageId?: Prisma.StringWithAggregatesFilter<"IncludedItems"> | string
}

export type IncludedItemsCreateInput = {
  id?: string
  item: string
  package: Prisma.PackageCreateNestedOneWithoutInclusionsInput
}

export type IncludedItemsUncheckedCreateInput = {
  id?: string
  item: string
  packageId: string
}

export type IncludedItemsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
  package?: Prisma.PackageUpdateOneRequiredWithoutInclusionsNestedInput
}

export type IncludedItemsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IncludedItemsCreateManyInput = {
  id?: string
  item: string
  packageId: string
}

export type IncludedItemsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IncludedItemsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
  packageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IncludedItemsListRelationFilter = {
  every?: Prisma.IncludedItemsWhereInput
  some?: Prisma.IncludedItemsWhereInput
  none?: Prisma.IncludedItemsWhereInput
}

export type IncludedItemsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IncludedItemsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type IncludedItemsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type IncludedItemsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  item?: Prisma.SortOrder
  packageId?: Prisma.SortOrder
}

export type IncludedItemsCreateNestedManyWithoutPackageInput = {
  create?: Prisma.XOR<Prisma.IncludedItemsCreateWithoutPackageInput, Prisma.IncludedItemsUncheckedCreateWithoutPackageInput> | Prisma.IncludedItemsCreateWithoutPackageInput[] | Prisma.IncludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.IncludedItemsCreateOrConnectWithoutPackageInput | Prisma.IncludedItemsCreateOrConnectWithoutPackageInput[]
  createMany?: Prisma.IncludedItemsCreateManyPackageInputEnvelope
  connect?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
}

export type IncludedItemsUncheckedCreateNestedManyWithoutPackageInput = {
  create?: Prisma.XOR<Prisma.IncludedItemsCreateWithoutPackageInput, Prisma.IncludedItemsUncheckedCreateWithoutPackageInput> | Prisma.IncludedItemsCreateWithoutPackageInput[] | Prisma.IncludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.IncludedItemsCreateOrConnectWithoutPackageInput | Prisma.IncludedItemsCreateOrConnectWithoutPackageInput[]
  createMany?: Prisma.IncludedItemsCreateManyPackageInputEnvelope
  connect?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
}

export type IncludedItemsUpdateManyWithoutPackageNestedInput = {
  create?: Prisma.XOR<Prisma.IncludedItemsCreateWithoutPackageInput, Prisma.IncludedItemsUncheckedCreateWithoutPackageInput> | Prisma.IncludedItemsCreateWithoutPackageInput[] | Prisma.IncludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.IncludedItemsCreateOrConnectWithoutPackageInput | Prisma.IncludedItemsCreateOrConnectWithoutPackageInput[]
  upsert?: Prisma.IncludedItemsUpsertWithWhereUniqueWithoutPackageInput | Prisma.IncludedItemsUpsertWithWhereUniqueWithoutPackageInput[]
  createMany?: Prisma.IncludedItemsCreateManyPackageInputEnvelope
  set?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  disconnect?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  delete?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  connect?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  update?: Prisma.IncludedItemsUpdateWithWhereUniqueWithoutPackageInput | Prisma.IncludedItemsUpdateWithWhereUniqueWithoutPackageInput[]
  updateMany?: Prisma.IncludedItemsUpdateManyWithWhereWithoutPackageInput | Prisma.IncludedItemsUpdateManyWithWhereWithoutPackageInput[]
  deleteMany?: Prisma.IncludedItemsScalarWhereInput | Prisma.IncludedItemsScalarWhereInput[]
}

export type IncludedItemsUncheckedUpdateManyWithoutPackageNestedInput = {
  create?: Prisma.XOR<Prisma.IncludedItemsCreateWithoutPackageInput, Prisma.IncludedItemsUncheckedCreateWithoutPackageInput> | Prisma.IncludedItemsCreateWithoutPackageInput[] | Prisma.IncludedItemsUncheckedCreateWithoutPackageInput[]
  connectOrCreate?: Prisma.IncludedItemsCreateOrConnectWithoutPackageInput | Prisma.IncludedItemsCreateOrConnectWithoutPackageInput[]
  upsert?: Prisma.IncludedItemsUpsertWithWhereUniqueWithoutPackageInput | Prisma.IncludedItemsUpsertWithWhereUniqueWithoutPackageInput[]
  createMany?: Prisma.IncludedItemsCreateManyPackageInputEnvelope
  set?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  disconnect?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  delete?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  connect?: Prisma.IncludedItemsWhereUniqueInput | Prisma.IncludedItemsWhereUniqueInput[]
  update?: Prisma.IncludedItemsUpdateWithWhereUniqueWithoutPackageInput | Prisma.IncludedItemsUpdateWithWhereUniqueWithoutPackageInput[]
  updateMany?: Prisma.IncludedItemsUpdateManyWithWhereWithoutPackageInput | Prisma.IncludedItemsUpdateManyWithWhereWithoutPackageInput[]
  deleteMany?: Prisma.IncludedItemsScalarWhereInput | Prisma.IncludedItemsScalarWhereInput[]
}

export type IncludedItemsCreateWithoutPackageInput = {
  id?: string
  item: string
}

export type IncludedItemsUncheckedCreateWithoutPackageInput = {
  id?: string
  item: string
}

export type IncludedItemsCreateOrConnectWithoutPackageInput = {
  where: Prisma.IncludedItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.IncludedItemsCreateWithoutPackageInput, Prisma.IncludedItemsUncheckedCreateWithoutPackageInput>
}

export type IncludedItemsCreateManyPackageInputEnvelope = {
  data: Prisma.IncludedItemsCreateManyPackageInput | Prisma.IncludedItemsCreateManyPackageInput[]
  skipDuplicates?: boolean
}

export type IncludedItemsUpsertWithWhereUniqueWithoutPackageInput = {
  where: Prisma.IncludedItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.IncludedItemsUpdateWithoutPackageInput, Prisma.IncludedItemsUncheckedUpdateWithoutPackageInput>
  create: Prisma.XOR<Prisma.IncludedItemsCreateWithoutPackageInput, Prisma.IncludedItemsUncheckedCreateWithoutPackageInput>
}

export type IncludedItemsUpdateWithWhereUniqueWithoutPackageInput = {
  where: Prisma.IncludedItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.IncludedItemsUpdateWithoutPackageInput, Prisma.IncludedItemsUncheckedUpdateWithoutPackageInput>
}

export type IncludedItemsUpdateManyWithWhereWithoutPackageInput = {
  where: Prisma.IncludedItemsScalarWhereInput
  data: Prisma.XOR<Prisma.IncludedItemsUpdateManyMutationInput, Prisma.IncludedItemsUncheckedUpdateManyWithoutPackageInput>
}

export type IncludedItemsScalarWhereInput = {
  AND?: Prisma.IncludedItemsScalarWhereInput | Prisma.IncludedItemsScalarWhereInput[]
  OR?: Prisma.IncludedItemsScalarWhereInput[]
  NOT?: Prisma.IncludedItemsScalarWhereInput | Prisma.IncludedItemsScalarWhereInput[]
  id?: Prisma.StringFilter<"IncludedItems"> | string
  item?: Prisma.StringFilter<"IncludedItems"> | string
  packageId?: Prisma.StringFilter<"IncludedItems"> | string
}

export type IncludedItemsCreateManyPackageInput = {
  id?: string
  item: string
}

export type IncludedItemsUpdateWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IncludedItemsUncheckedUpdateWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IncludedItemsUncheckedUpdateManyWithoutPackageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  item?: Prisma.StringFieldUpdateOperationsInput | string
}



export type IncludedItemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  item?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["includedItems"]>

export type IncludedItemsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  item?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["includedItems"]>

export type IncludedItemsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  item?: boolean
  packageId?: boolean
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["includedItems"]>

export type IncludedItemsSelectScalar = {
  id?: boolean
  item?: boolean
  packageId?: boolean
}

export type IncludedItemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "item" | "packageId", ExtArgs["result"]["includedItems"]>
export type IncludedItemsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}
export type IncludedItemsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}
export type IncludedItemsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  package?: boolean | Prisma.PackageDefaultArgs<ExtArgs>
}

export type $IncludedItemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "IncludedItems"
  objects: {
    package: Prisma.$PackagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    item: string
    packageId: string
  }, ExtArgs["result"]["includedItems"]>
  composites: {}
}

export type IncludedItemsGetPayload<S extends boolean | null | undefined | IncludedItemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload, S>

export type IncludedItemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IncludedItemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IncludedItemsCountAggregateInputType | true
  }

export interface IncludedItemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['IncludedItems'], meta: { name: 'IncludedItems' } }
  /**
   * Find zero or one IncludedItems that matches the filter.
   * @param {IncludedItemsFindUniqueArgs} args - Arguments to find a IncludedItems
   * @example
   * // Get one IncludedItems
   * const includedItems = await prisma.includedItems.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IncludedItemsFindUniqueArgs>(args: Prisma.SelectSubset<T, IncludedItemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one IncludedItems that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IncludedItemsFindUniqueOrThrowArgs} args - Arguments to find a IncludedItems
   * @example
   * // Get one IncludedItems
   * const includedItems = await prisma.includedItems.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IncludedItemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IncludedItemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IncludedItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsFindFirstArgs} args - Arguments to find a IncludedItems
   * @example
   * // Get one IncludedItems
   * const includedItems = await prisma.includedItems.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IncludedItemsFindFirstArgs>(args?: Prisma.SelectSubset<T, IncludedItemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IncludedItems that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsFindFirstOrThrowArgs} args - Arguments to find a IncludedItems
   * @example
   * // Get one IncludedItems
   * const includedItems = await prisma.includedItems.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IncludedItemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IncludedItemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more IncludedItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all IncludedItems
   * const includedItems = await prisma.includedItems.findMany()
   * 
   * // Get first 10 IncludedItems
   * const includedItems = await prisma.includedItems.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const includedItemsWithIdOnly = await prisma.includedItems.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IncludedItemsFindManyArgs>(args?: Prisma.SelectSubset<T, IncludedItemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a IncludedItems.
   * @param {IncludedItemsCreateArgs} args - Arguments to create a IncludedItems.
   * @example
   * // Create one IncludedItems
   * const IncludedItems = await prisma.includedItems.create({
   *   data: {
   *     // ... data to create a IncludedItems
   *   }
   * })
   * 
   */
  create<T extends IncludedItemsCreateArgs>(args: Prisma.SelectSubset<T, IncludedItemsCreateArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many IncludedItems.
   * @param {IncludedItemsCreateManyArgs} args - Arguments to create many IncludedItems.
   * @example
   * // Create many IncludedItems
   * const includedItems = await prisma.includedItems.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IncludedItemsCreateManyArgs>(args?: Prisma.SelectSubset<T, IncludedItemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many IncludedItems and returns the data saved in the database.
   * @param {IncludedItemsCreateManyAndReturnArgs} args - Arguments to create many IncludedItems.
   * @example
   * // Create many IncludedItems
   * const includedItems = await prisma.includedItems.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many IncludedItems and only return the `id`
   * const includedItemsWithIdOnly = await prisma.includedItems.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IncludedItemsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IncludedItemsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a IncludedItems.
   * @param {IncludedItemsDeleteArgs} args - Arguments to delete one IncludedItems.
   * @example
   * // Delete one IncludedItems
   * const IncludedItems = await prisma.includedItems.delete({
   *   where: {
   *     // ... filter to delete one IncludedItems
   *   }
   * })
   * 
   */
  delete<T extends IncludedItemsDeleteArgs>(args: Prisma.SelectSubset<T, IncludedItemsDeleteArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one IncludedItems.
   * @param {IncludedItemsUpdateArgs} args - Arguments to update one IncludedItems.
   * @example
   * // Update one IncludedItems
   * const includedItems = await prisma.includedItems.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IncludedItemsUpdateArgs>(args: Prisma.SelectSubset<T, IncludedItemsUpdateArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more IncludedItems.
   * @param {IncludedItemsDeleteManyArgs} args - Arguments to filter IncludedItems to delete.
   * @example
   * // Delete a few IncludedItems
   * const { count } = await prisma.includedItems.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IncludedItemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, IncludedItemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IncludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many IncludedItems
   * const includedItems = await prisma.includedItems.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IncludedItemsUpdateManyArgs>(args: Prisma.SelectSubset<T, IncludedItemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IncludedItems and returns the data updated in the database.
   * @param {IncludedItemsUpdateManyAndReturnArgs} args - Arguments to update many IncludedItems.
   * @example
   * // Update many IncludedItems
   * const includedItems = await prisma.includedItems.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more IncludedItems and only return the `id`
   * const includedItemsWithIdOnly = await prisma.includedItems.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IncludedItemsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IncludedItemsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one IncludedItems.
   * @param {IncludedItemsUpsertArgs} args - Arguments to update or create a IncludedItems.
   * @example
   * // Update or create a IncludedItems
   * const includedItems = await prisma.includedItems.upsert({
   *   create: {
   *     // ... data to create a IncludedItems
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the IncludedItems we want to update
   *   }
   * })
   */
  upsert<T extends IncludedItemsUpsertArgs>(args: Prisma.SelectSubset<T, IncludedItemsUpsertArgs<ExtArgs>>): Prisma.Prisma__IncludedItemsClient<runtime.Types.Result.GetResult<Prisma.$IncludedItemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of IncludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsCountArgs} args - Arguments to filter IncludedItems to count.
   * @example
   * // Count the number of IncludedItems
   * const count = await prisma.includedItems.count({
   *   where: {
   *     // ... the filter for the IncludedItems we want to count
   *   }
   * })
  **/
  count<T extends IncludedItemsCountArgs>(
    args?: Prisma.Subset<T, IncludedItemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IncludedItemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a IncludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IncludedItemsAggregateArgs>(args: Prisma.Subset<T, IncludedItemsAggregateArgs>): Prisma.PrismaPromise<GetIncludedItemsAggregateType<T>>

  /**
   * Group by IncludedItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncludedItemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IncludedItemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IncludedItemsGroupByArgs['orderBy'] }
      : { orderBy?: IncludedItemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IncludedItemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIncludedItemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the IncludedItems model
 */
readonly fields: IncludedItemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for IncludedItems.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IncludedItemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  package<T extends Prisma.PackageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PackageDefaultArgs<ExtArgs>>): Prisma.Prisma__PackageClient<runtime.Types.Result.GetResult<Prisma.$PackagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the IncludedItems model
 */
export interface IncludedItemsFieldRefs {
  readonly id: Prisma.FieldRef<"IncludedItems", 'String'>
  readonly item: Prisma.FieldRef<"IncludedItems", 'String'>
  readonly packageId: Prisma.FieldRef<"IncludedItems", 'String'>
}
    

// Custom InputTypes
/**
 * IncludedItems findUnique
 */
export type IncludedItemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which IncludedItems to fetch.
   */
  where: Prisma.IncludedItemsWhereUniqueInput
}

/**
 * IncludedItems findUniqueOrThrow
 */
export type IncludedItemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which IncludedItems to fetch.
   */
  where: Prisma.IncludedItemsWhereUniqueInput
}

/**
 * IncludedItems findFirst
 */
export type IncludedItemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which IncludedItems to fetch.
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IncludedItems to fetch.
   */
  orderBy?: Prisma.IncludedItemsOrderByWithRelationInput | Prisma.IncludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IncludedItems.
   */
  cursor?: Prisma.IncludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IncludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IncludedItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IncludedItems.
   */
  distinct?: Prisma.IncludedItemsScalarFieldEnum | Prisma.IncludedItemsScalarFieldEnum[]
}

/**
 * IncludedItems findFirstOrThrow
 */
export type IncludedItemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which IncludedItems to fetch.
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IncludedItems to fetch.
   */
  orderBy?: Prisma.IncludedItemsOrderByWithRelationInput | Prisma.IncludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IncludedItems.
   */
  cursor?: Prisma.IncludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IncludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IncludedItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IncludedItems.
   */
  distinct?: Prisma.IncludedItemsScalarFieldEnum | Prisma.IncludedItemsScalarFieldEnum[]
}

/**
 * IncludedItems findMany
 */
export type IncludedItemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * Filter, which IncludedItems to fetch.
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IncludedItems to fetch.
   */
  orderBy?: Prisma.IncludedItemsOrderByWithRelationInput | Prisma.IncludedItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing IncludedItems.
   */
  cursor?: Prisma.IncludedItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IncludedItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IncludedItems.
   */
  skip?: number
  distinct?: Prisma.IncludedItemsScalarFieldEnum | Prisma.IncludedItemsScalarFieldEnum[]
}

/**
 * IncludedItems create
 */
export type IncludedItemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * The data needed to create a IncludedItems.
   */
  data: Prisma.XOR<Prisma.IncludedItemsCreateInput, Prisma.IncludedItemsUncheckedCreateInput>
}

/**
 * IncludedItems createMany
 */
export type IncludedItemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many IncludedItems.
   */
  data: Prisma.IncludedItemsCreateManyInput | Prisma.IncludedItemsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * IncludedItems createManyAndReturn
 */
export type IncludedItemsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * The data used to create many IncludedItems.
   */
  data: Prisma.IncludedItemsCreateManyInput | Prisma.IncludedItemsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * IncludedItems update
 */
export type IncludedItemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * The data needed to update a IncludedItems.
   */
  data: Prisma.XOR<Prisma.IncludedItemsUpdateInput, Prisma.IncludedItemsUncheckedUpdateInput>
  /**
   * Choose, which IncludedItems to update.
   */
  where: Prisma.IncludedItemsWhereUniqueInput
}

/**
 * IncludedItems updateMany
 */
export type IncludedItemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update IncludedItems.
   */
  data: Prisma.XOR<Prisma.IncludedItemsUpdateManyMutationInput, Prisma.IncludedItemsUncheckedUpdateManyInput>
  /**
   * Filter which IncludedItems to update
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * Limit how many IncludedItems to update.
   */
  limit?: number
}

/**
 * IncludedItems updateManyAndReturn
 */
export type IncludedItemsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * The data used to update IncludedItems.
   */
  data: Prisma.XOR<Prisma.IncludedItemsUpdateManyMutationInput, Prisma.IncludedItemsUncheckedUpdateManyInput>
  /**
   * Filter which IncludedItems to update
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * Limit how many IncludedItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * IncludedItems upsert
 */
export type IncludedItemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * The filter to search for the IncludedItems to update in case it exists.
   */
  where: Prisma.IncludedItemsWhereUniqueInput
  /**
   * In case the IncludedItems found by the `where` argument doesn't exist, create a new IncludedItems with this data.
   */
  create: Prisma.XOR<Prisma.IncludedItemsCreateInput, Prisma.IncludedItemsUncheckedCreateInput>
  /**
   * In case the IncludedItems was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IncludedItemsUpdateInput, Prisma.IncludedItemsUncheckedUpdateInput>
}

/**
 * IncludedItems delete
 */
export type IncludedItemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
  /**
   * Filter which IncludedItems to delete.
   */
  where: Prisma.IncludedItemsWhereUniqueInput
}

/**
 * IncludedItems deleteMany
 */
export type IncludedItemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IncludedItems to delete
   */
  where?: Prisma.IncludedItemsWhereInput
  /**
   * Limit how many IncludedItems to delete.
   */
  limit?: number
}

/**
 * IncludedItems without action
 */
export type IncludedItemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IncludedItems
   */
  select?: Prisma.IncludedItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IncludedItems
   */
  omit?: Prisma.IncludedItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncludedItemsInclude<ExtArgs> | null
}
