
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Testimonials` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Testimonials
 * 
 */
export type TestimonialsModel = runtime.Types.Result.DefaultSelection<Prisma.$TestimonialsPayload>

export type AggregateTestimonials = {
  _count: TestimonialsCountAggregateOutputType | null
  _avg: TestimonialsAvgAggregateOutputType | null
  _sum: TestimonialsSumAggregateOutputType | null
  _min: TestimonialsMinAggregateOutputType | null
  _max: TestimonialsMaxAggregateOutputType | null
}

export type TestimonialsAvgAggregateOutputType = {
  rating: number | null
}

export type TestimonialsSumAggregateOutputType = {
  rating: number | null
}

export type TestimonialsMinAggregateOutputType = {
  id: string | null
  customerName: string | null
  feedback: string | null
  rating: number | null
  image: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TestimonialsMaxAggregateOutputType = {
  id: string | null
  customerName: string | null
  feedback: string | null
  rating: number | null
  image: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TestimonialsCountAggregateOutputType = {
  id: number
  customerName: number
  feedback: number
  rating: number
  image: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TestimonialsAvgAggregateInputType = {
  rating?: true
}

export type TestimonialsSumAggregateInputType = {
  rating?: true
}

export type TestimonialsMinAggregateInputType = {
  id?: true
  customerName?: true
  feedback?: true
  rating?: true
  image?: true
  createdAt?: true
  updatedAt?: true
}

export type TestimonialsMaxAggregateInputType = {
  id?: true
  customerName?: true
  feedback?: true
  rating?: true
  image?: true
  createdAt?: true
  updatedAt?: true
}

export type TestimonialsCountAggregateInputType = {
  id?: true
  customerName?: true
  feedback?: true
  rating?: true
  image?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TestimonialsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Testimonials to aggregate.
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Testimonials to fetch.
   */
  orderBy?: Prisma.TestimonialsOrderByWithRelationInput | Prisma.TestimonialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TestimonialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Testimonials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Testimonials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Testimonials
  **/
  _count?: true | TestimonialsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TestimonialsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TestimonialsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TestimonialsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TestimonialsMaxAggregateInputType
}

export type GetTestimonialsAggregateType<T extends TestimonialsAggregateArgs> = {
      [P in keyof T & keyof AggregateTestimonials]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTestimonials[P]>
    : Prisma.GetScalarType<T[P], AggregateTestimonials[P]>
}




export type TestimonialsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TestimonialsWhereInput
  orderBy?: Prisma.TestimonialsOrderByWithAggregationInput | Prisma.TestimonialsOrderByWithAggregationInput[]
  by: Prisma.TestimonialsScalarFieldEnum[] | Prisma.TestimonialsScalarFieldEnum
  having?: Prisma.TestimonialsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TestimonialsCountAggregateInputType | true
  _avg?: TestimonialsAvgAggregateInputType
  _sum?: TestimonialsSumAggregateInputType
  _min?: TestimonialsMinAggregateInputType
  _max?: TestimonialsMaxAggregateInputType
}

export type TestimonialsGroupByOutputType = {
  id: string
  customerName: string
  feedback: string
  rating: number
  image: string | null
  createdAt: Date
  updatedAt: Date
  _count: TestimonialsCountAggregateOutputType | null
  _avg: TestimonialsAvgAggregateOutputType | null
  _sum: TestimonialsSumAggregateOutputType | null
  _min: TestimonialsMinAggregateOutputType | null
  _max: TestimonialsMaxAggregateOutputType | null
}

type GetTestimonialsGroupByPayload<T extends TestimonialsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TestimonialsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TestimonialsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TestimonialsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TestimonialsGroupByOutputType[P]>
      }
    >
  >



export type TestimonialsWhereInput = {
  AND?: Prisma.TestimonialsWhereInput | Prisma.TestimonialsWhereInput[]
  OR?: Prisma.TestimonialsWhereInput[]
  NOT?: Prisma.TestimonialsWhereInput | Prisma.TestimonialsWhereInput[]
  id?: Prisma.StringFilter<"Testimonials"> | string
  customerName?: Prisma.StringFilter<"Testimonials"> | string
  feedback?: Prisma.StringFilter<"Testimonials"> | string
  rating?: Prisma.IntFilter<"Testimonials"> | number
  image?: Prisma.StringNullableFilter<"Testimonials"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Testimonials"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Testimonials"> | Date | string
}

export type TestimonialsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TestimonialsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TestimonialsWhereInput | Prisma.TestimonialsWhereInput[]
  OR?: Prisma.TestimonialsWhereInput[]
  NOT?: Prisma.TestimonialsWhereInput | Prisma.TestimonialsWhereInput[]
  customerName?: Prisma.StringFilter<"Testimonials"> | string
  feedback?: Prisma.StringFilter<"Testimonials"> | string
  rating?: Prisma.IntFilter<"Testimonials"> | number
  image?: Prisma.StringNullableFilter<"Testimonials"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Testimonials"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Testimonials"> | Date | string
}, "id">

export type TestimonialsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TestimonialsCountOrderByAggregateInput
  _avg?: Prisma.TestimonialsAvgOrderByAggregateInput
  _max?: Prisma.TestimonialsMaxOrderByAggregateInput
  _min?: Prisma.TestimonialsMinOrderByAggregateInput
  _sum?: Prisma.TestimonialsSumOrderByAggregateInput
}

export type TestimonialsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TestimonialsScalarWhereWithAggregatesInput | Prisma.TestimonialsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TestimonialsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TestimonialsScalarWhereWithAggregatesInput | Prisma.TestimonialsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Testimonials"> | string
  customerName?: Prisma.StringWithAggregatesFilter<"Testimonials"> | string
  feedback?: Prisma.StringWithAggregatesFilter<"Testimonials"> | string
  rating?: Prisma.IntWithAggregatesFilter<"Testimonials"> | number
  image?: Prisma.StringNullableWithAggregatesFilter<"Testimonials"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Testimonials"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Testimonials"> | Date | string
}

export type TestimonialsCreateInput = {
  id?: string
  customerName: string
  feedback: string
  rating: number
  image?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TestimonialsUncheckedCreateInput = {
  id?: string
  customerName: string
  feedback: string
  rating: number
  image?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TestimonialsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestimonialsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestimonialsCreateManyInput = {
  id?: string
  customerName: string
  feedback: string
  rating: number
  image?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TestimonialsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestimonialsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestimonialsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TestimonialsAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type TestimonialsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TestimonialsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TestimonialsSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}



export type TestimonialsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerName?: boolean
  feedback?: boolean
  rating?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["testimonials"]>

export type TestimonialsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerName?: boolean
  feedback?: boolean
  rating?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["testimonials"]>

export type TestimonialsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerName?: boolean
  feedback?: boolean
  rating?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["testimonials"]>

export type TestimonialsSelectScalar = {
  id?: boolean
  customerName?: boolean
  feedback?: boolean
  rating?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TestimonialsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "customerName" | "feedback" | "rating" | "image" | "createdAt" | "updatedAt", ExtArgs["result"]["testimonials"]>

export type $TestimonialsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Testimonials"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    customerName: string
    feedback: string
    rating: number
    image: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["testimonials"]>
  composites: {}
}

export type TestimonialsGetPayload<S extends boolean | null | undefined | TestimonialsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload, S>

export type TestimonialsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TestimonialsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TestimonialsCountAggregateInputType | true
  }

export interface TestimonialsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Testimonials'], meta: { name: 'Testimonials' } }
  /**
   * Find zero or one Testimonials that matches the filter.
   * @param {TestimonialsFindUniqueArgs} args - Arguments to find a Testimonials
   * @example
   * // Get one Testimonials
   * const testimonials = await prisma.testimonials.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TestimonialsFindUniqueArgs>(args: Prisma.SelectSubset<T, TestimonialsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Testimonials that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TestimonialsFindUniqueOrThrowArgs} args - Arguments to find a Testimonials
   * @example
   * // Get one Testimonials
   * const testimonials = await prisma.testimonials.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TestimonialsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TestimonialsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Testimonials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsFindFirstArgs} args - Arguments to find a Testimonials
   * @example
   * // Get one Testimonials
   * const testimonials = await prisma.testimonials.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TestimonialsFindFirstArgs>(args?: Prisma.SelectSubset<T, TestimonialsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Testimonials that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsFindFirstOrThrowArgs} args - Arguments to find a Testimonials
   * @example
   * // Get one Testimonials
   * const testimonials = await prisma.testimonials.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TestimonialsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TestimonialsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Testimonials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Testimonials
   * const testimonials = await prisma.testimonials.findMany()
   * 
   * // Get first 10 Testimonials
   * const testimonials = await prisma.testimonials.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const testimonialsWithIdOnly = await prisma.testimonials.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TestimonialsFindManyArgs>(args?: Prisma.SelectSubset<T, TestimonialsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Testimonials.
   * @param {TestimonialsCreateArgs} args - Arguments to create a Testimonials.
   * @example
   * // Create one Testimonials
   * const Testimonials = await prisma.testimonials.create({
   *   data: {
   *     // ... data to create a Testimonials
   *   }
   * })
   * 
   */
  create<T extends TestimonialsCreateArgs>(args: Prisma.SelectSubset<T, TestimonialsCreateArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Testimonials.
   * @param {TestimonialsCreateManyArgs} args - Arguments to create many Testimonials.
   * @example
   * // Create many Testimonials
   * const testimonials = await prisma.testimonials.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TestimonialsCreateManyArgs>(args?: Prisma.SelectSubset<T, TestimonialsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Testimonials and returns the data saved in the database.
   * @param {TestimonialsCreateManyAndReturnArgs} args - Arguments to create many Testimonials.
   * @example
   * // Create many Testimonials
   * const testimonials = await prisma.testimonials.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Testimonials and only return the `id`
   * const testimonialsWithIdOnly = await prisma.testimonials.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TestimonialsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TestimonialsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Testimonials.
   * @param {TestimonialsDeleteArgs} args - Arguments to delete one Testimonials.
   * @example
   * // Delete one Testimonials
   * const Testimonials = await prisma.testimonials.delete({
   *   where: {
   *     // ... filter to delete one Testimonials
   *   }
   * })
   * 
   */
  delete<T extends TestimonialsDeleteArgs>(args: Prisma.SelectSubset<T, TestimonialsDeleteArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Testimonials.
   * @param {TestimonialsUpdateArgs} args - Arguments to update one Testimonials.
   * @example
   * // Update one Testimonials
   * const testimonials = await prisma.testimonials.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TestimonialsUpdateArgs>(args: Prisma.SelectSubset<T, TestimonialsUpdateArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Testimonials.
   * @param {TestimonialsDeleteManyArgs} args - Arguments to filter Testimonials to delete.
   * @example
   * // Delete a few Testimonials
   * const { count } = await prisma.testimonials.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TestimonialsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TestimonialsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Testimonials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Testimonials
   * const testimonials = await prisma.testimonials.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TestimonialsUpdateManyArgs>(args: Prisma.SelectSubset<T, TestimonialsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Testimonials and returns the data updated in the database.
   * @param {TestimonialsUpdateManyAndReturnArgs} args - Arguments to update many Testimonials.
   * @example
   * // Update many Testimonials
   * const testimonials = await prisma.testimonials.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Testimonials and only return the `id`
   * const testimonialsWithIdOnly = await prisma.testimonials.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TestimonialsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TestimonialsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Testimonials.
   * @param {TestimonialsUpsertArgs} args - Arguments to update or create a Testimonials.
   * @example
   * // Update or create a Testimonials
   * const testimonials = await prisma.testimonials.upsert({
   *   create: {
   *     // ... data to create a Testimonials
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Testimonials we want to update
   *   }
   * })
   */
  upsert<T extends TestimonialsUpsertArgs>(args: Prisma.SelectSubset<T, TestimonialsUpsertArgs<ExtArgs>>): Prisma.Prisma__TestimonialsClient<runtime.Types.Result.GetResult<Prisma.$TestimonialsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Testimonials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsCountArgs} args - Arguments to filter Testimonials to count.
   * @example
   * // Count the number of Testimonials
   * const count = await prisma.testimonials.count({
   *   where: {
   *     // ... the filter for the Testimonials we want to count
   *   }
   * })
  **/
  count<T extends TestimonialsCountArgs>(
    args?: Prisma.Subset<T, TestimonialsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TestimonialsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Testimonials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TestimonialsAggregateArgs>(args: Prisma.Subset<T, TestimonialsAggregateArgs>): Prisma.PrismaPromise<GetTestimonialsAggregateType<T>>

  /**
   * Group by Testimonials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestimonialsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TestimonialsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TestimonialsGroupByArgs['orderBy'] }
      : { orderBy?: TestimonialsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TestimonialsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTestimonialsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Testimonials model
 */
readonly fields: TestimonialsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Testimonials.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TestimonialsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Testimonials model
 */
export interface TestimonialsFieldRefs {
  readonly id: Prisma.FieldRef<"Testimonials", 'String'>
  readonly customerName: Prisma.FieldRef<"Testimonials", 'String'>
  readonly feedback: Prisma.FieldRef<"Testimonials", 'String'>
  readonly rating: Prisma.FieldRef<"Testimonials", 'Int'>
  readonly image: Prisma.FieldRef<"Testimonials", 'String'>
  readonly createdAt: Prisma.FieldRef<"Testimonials", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Testimonials", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Testimonials findUnique
 */
export type TestimonialsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * Filter, which Testimonials to fetch.
   */
  where: Prisma.TestimonialsWhereUniqueInput
}

/**
 * Testimonials findUniqueOrThrow
 */
export type TestimonialsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * Filter, which Testimonials to fetch.
   */
  where: Prisma.TestimonialsWhereUniqueInput
}

/**
 * Testimonials findFirst
 */
export type TestimonialsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * Filter, which Testimonials to fetch.
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Testimonials to fetch.
   */
  orderBy?: Prisma.TestimonialsOrderByWithRelationInput | Prisma.TestimonialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Testimonials.
   */
  cursor?: Prisma.TestimonialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Testimonials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Testimonials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Testimonials.
   */
  distinct?: Prisma.TestimonialsScalarFieldEnum | Prisma.TestimonialsScalarFieldEnum[]
}

/**
 * Testimonials findFirstOrThrow
 */
export type TestimonialsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * Filter, which Testimonials to fetch.
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Testimonials to fetch.
   */
  orderBy?: Prisma.TestimonialsOrderByWithRelationInput | Prisma.TestimonialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Testimonials.
   */
  cursor?: Prisma.TestimonialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Testimonials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Testimonials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Testimonials.
   */
  distinct?: Prisma.TestimonialsScalarFieldEnum | Prisma.TestimonialsScalarFieldEnum[]
}

/**
 * Testimonials findMany
 */
export type TestimonialsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * Filter, which Testimonials to fetch.
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Testimonials to fetch.
   */
  orderBy?: Prisma.TestimonialsOrderByWithRelationInput | Prisma.TestimonialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Testimonials.
   */
  cursor?: Prisma.TestimonialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Testimonials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Testimonials.
   */
  skip?: number
  distinct?: Prisma.TestimonialsScalarFieldEnum | Prisma.TestimonialsScalarFieldEnum[]
}

/**
 * Testimonials create
 */
export type TestimonialsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * The data needed to create a Testimonials.
   */
  data: Prisma.XOR<Prisma.TestimonialsCreateInput, Prisma.TestimonialsUncheckedCreateInput>
}

/**
 * Testimonials createMany
 */
export type TestimonialsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Testimonials.
   */
  data: Prisma.TestimonialsCreateManyInput | Prisma.TestimonialsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Testimonials createManyAndReturn
 */
export type TestimonialsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * The data used to create many Testimonials.
   */
  data: Prisma.TestimonialsCreateManyInput | Prisma.TestimonialsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Testimonials update
 */
export type TestimonialsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * The data needed to update a Testimonials.
   */
  data: Prisma.XOR<Prisma.TestimonialsUpdateInput, Prisma.TestimonialsUncheckedUpdateInput>
  /**
   * Choose, which Testimonials to update.
   */
  where: Prisma.TestimonialsWhereUniqueInput
}

/**
 * Testimonials updateMany
 */
export type TestimonialsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Testimonials.
   */
  data: Prisma.XOR<Prisma.TestimonialsUpdateManyMutationInput, Prisma.TestimonialsUncheckedUpdateManyInput>
  /**
   * Filter which Testimonials to update
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * Limit how many Testimonials to update.
   */
  limit?: number
}

/**
 * Testimonials updateManyAndReturn
 */
export type TestimonialsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * The data used to update Testimonials.
   */
  data: Prisma.XOR<Prisma.TestimonialsUpdateManyMutationInput, Prisma.TestimonialsUncheckedUpdateManyInput>
  /**
   * Filter which Testimonials to update
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * Limit how many Testimonials to update.
   */
  limit?: number
}

/**
 * Testimonials upsert
 */
export type TestimonialsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * The filter to search for the Testimonials to update in case it exists.
   */
  where: Prisma.TestimonialsWhereUniqueInput
  /**
   * In case the Testimonials found by the `where` argument doesn't exist, create a new Testimonials with this data.
   */
  create: Prisma.XOR<Prisma.TestimonialsCreateInput, Prisma.TestimonialsUncheckedCreateInput>
  /**
   * In case the Testimonials was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TestimonialsUpdateInput, Prisma.TestimonialsUncheckedUpdateInput>
}

/**
 * Testimonials delete
 */
export type TestimonialsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
  /**
   * Filter which Testimonials to delete.
   */
  where: Prisma.TestimonialsWhereUniqueInput
}

/**
 * Testimonials deleteMany
 */
export type TestimonialsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Testimonials to delete
   */
  where?: Prisma.TestimonialsWhereInput
  /**
   * Limit how many Testimonials to delete.
   */
  limit?: number
}

/**
 * Testimonials without action
 */
export type TestimonialsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Testimonials
   */
  select?: Prisma.TestimonialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Testimonials
   */
  omit?: Prisma.TestimonialsOmit<ExtArgs> | null
}
